[project]
name = "zalfmas-capnp-schemas"
version = "0.1.66"
description = ""
readme = "README.md"
requires-python = ">=3.12,<3.14"
authors = [{ name = "Michael Berg-Mohnicke", email = "michael.berg@zalf.de" }]
dependencies = ["pycapnp>=2.2.2,<3"]

[dependency-groups]
dev = [
  "capnp-stub-generator @ git+https://github.com/zalf-rpm/capnp-stub-generator.git",
  "ruff>=0.15.15,<0.16",
  "ty>=0.0.40,<0.0.41",
]

[tool.pixi.feature.dev.dependencies]
pixi-pycharm = ">=0.0.11,<0.0.12"

[tool.pixi.environments]
dev = ["dev"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]
preview = ["pixi-build"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "*", from = "gen/python" }]


[tool.ruff]
target-version = "py313"
[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = ["E501"]
