"""This is an automatically generated stub for `service.capnp`."""

from __future__ import annotations

from collections.abc import Awaitable, Iterator, Sequence
from contextlib import contextmanager
from io import BufferedWriter
from typing import Any, BinaryIO, Generic, Literal, Protocol, TypeVar

from capnp import _DynamicListBuilder

from .common_capnp import Identifiable, Pair, PairBuilder, PairReader

Factory_Payload = TypeVar("Factory_Payload")

class Admin(Identifiable, Protocol):
    def heartbeat(self) -> None: ...
    class HeartbeatRequest(Protocol):
        def send(self) -> Any: ...

    def heartbeat_request(self) -> HeartbeatRequest: ...
    def setTimeout(self, seconds: int) -> None: ...
    class SettimeoutRequest(Protocol):
        seconds: int
        def send(self) -> Any: ...

    def setTimeout_request(self) -> SettimeoutRequest: ...
    def stop(self) -> None: ...
    class StopRequest(Protocol):
        def send(self) -> Any: ...

    def stop_request(self) -> StopRequest: ...
    class IdentitiesResult(Awaitable[IdentitiesResult], Protocol):
        infos: Any

    def identities(self) -> IdentitiesResult: ...
    class IdentitiesRequest(Protocol):
        def send(self) -> Admin.IdentitiesResult: ...

    def identities_request(self) -> IdentitiesRequest: ...
    def updateIdentity(self, oldId: str, newInfo: Any) -> None: ...
    class UpdateidentityRequest(Protocol):
        oldId: str
        newInfo: Any
        def send(self) -> Any: ...

    def updateIdentity_request(self) -> UpdateidentityRequest: ...
    class Server(Identifiable.Server):
        def heartbeat(self, **kwargs) -> None: ...
        def setTimeout(self, seconds: int, **kwargs) -> None: ...
        def stop(self, **kwargs) -> None: ...
        def identities(self, **kwargs) -> Awaitable[Any]: ...
        def updateIdentity(self, oldId: str, newInfo: Any, **kwargs) -> None: ...

class SimpleFactory(Identifiable, Protocol):
    class CreateResult(Awaitable[CreateResult], Protocol):
        caps: Sequence[Identifiable]

    def create(self) -> CreateResult: ...
    class CreateRequest(Protocol):
        def send(self) -> SimpleFactory.CreateResult: ...

    def create_request(self) -> CreateRequest: ...
    class Server(Identifiable.Server):
        def create(self, **kwargs) -> Awaitable[Sequence[Identifiable]]: ...

class Factory(Identifiable, Protocol):
    class CreateParams(Generic[Factory_Payload]):
        @property
        def timeoutSeconds(self) -> int: ...
        @property
        def interfaceNameToRegistrySR(self) -> Sequence[Pair]: ...
        @property
        def msgPayload(self) -> Factory_Payload: ...
        @staticmethod
        @contextmanager
        def from_bytes(
            data: bytes,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> Iterator[Factory.CreateParamsReader]: ...
        @staticmethod
        def from_bytes_packed(
            data: bytes,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> Factory.CreateParamsReader: ...
        @staticmethod
        def new_message(
            num_first_segment_words: int | None = None,
            allocate_seg_callable: Any = None,
            timeoutSeconds: int | None = None,
            interfaceNameToRegistrySR: Sequence[PairBuilder] | None = None,
            msgPayload: Factory_Payload | None = None,
        ) -> Factory.CreateParamsBuilder: ...
        @staticmethod
        def read(
            file: BinaryIO,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> Factory.CreateParamsReader: ...
        @staticmethod
        def read_packed(
            file: BinaryIO,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> Factory.CreateParamsReader: ...
        def to_dict(self) -> dict: ...

    class CreateParamsReader(Factory.CreateParams, Generic[Factory_Payload]):
        @property
        def interfaceNameToRegistrySR(self) -> Sequence[PairReader]: ...
        def as_builder(self) -> Factory.CreateParamsBuilder: ...

    class CreateParamsBuilder(Factory.CreateParams, Generic[Factory_Payload]):
        @property
        def timeoutSeconds(self) -> int: ...
        @timeoutSeconds.setter
        def timeoutSeconds(self, value: int) -> None: ...
        @property
        def interfaceNameToRegistrySR(self) -> Sequence[PairBuilder]: ...
        @interfaceNameToRegistrySR.setter
        def interfaceNameToRegistrySR(
            self, value: Sequence[Pair | PairBuilder | PairReader]
        ) -> None: ...
        @property
        def msgPayload(self) -> Factory_Payload: ...
        @msgPayload.setter
        def msgPayload(self, value: Factory_Payload) -> None: ...
        @staticmethod
        def from_dict(dictionary: dict) -> Factory.CreateParamsBuilder: ...
        def init(
            self: Any, name: Literal["interfaceNameToRegistrySR"], size: int = ...
        ) -> _DynamicListBuilder[PairBuilder]: ...
        def copy(self) -> Factory.CreateParamsBuilder: ...
        def to_bytes(self) -> bytes: ...
        def to_bytes_packed(self) -> bytes: ...
        def to_segments(self) -> list[bytes]: ...
        def as_reader(self) -> Factory.CreateParamsReader: ...
        @staticmethod
        def write(file: BufferedWriter) -> None: ...
        @staticmethod
        def write_packed(file: BufferedWriter) -> None: ...

    class AccessInfo:
        @property
        def adminCap(self) -> Any: ...
        @property
        def serviceCaps(self) -> Sequence[Identifiable]: ...
        @property
        def error(self) -> str: ...
        @staticmethod
        @contextmanager
        def from_bytes(
            data: bytes,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> Iterator[Factory.AccessInfoReader]: ...
        @staticmethod
        def from_bytes_packed(
            data: bytes,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> Factory.AccessInfoReader: ...
        @staticmethod
        def new_message(
            num_first_segment_words: int | None = None,
            allocate_seg_callable: Any = None,
            adminCap: Any | None = None,
            serviceCaps: Sequence[Identifiable] | None = None,
            error: str | None = None,
        ) -> Factory.AccessInfoBuilder: ...
        @staticmethod
        def read(
            file: BinaryIO,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> Factory.AccessInfoReader: ...
        @staticmethod
        def read_packed(
            file: BinaryIO,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> Factory.AccessInfoReader: ...
        def to_dict(self) -> dict: ...

    class AccessInfoReader(Factory.AccessInfo):
        def as_builder(self) -> Factory.AccessInfoBuilder: ...

    class AccessInfoBuilder(Factory.AccessInfo):
        @property
        def adminCap(self) -> Any: ...
        @adminCap.setter
        def adminCap(self, value: Any) -> None: ...
        @property
        def serviceCaps(self) -> Sequence[Identifiable]: ...
        @serviceCaps.setter
        def serviceCaps(self, value: Sequence[Identifiable]) -> None: ...
        @property
        def error(self) -> str: ...
        @error.setter
        def error(self, value: str) -> None: ...
        @staticmethod
        def from_dict(dictionary: dict) -> Factory.AccessInfoBuilder: ...
        def init(
            self: Any, name: Literal["serviceCaps"], size: int = ...
        ) -> _DynamicListBuilder[Identifiable]: ...
        def copy(self) -> Factory.AccessInfoBuilder: ...
        def to_bytes(self) -> bytes: ...
        def to_bytes_packed(self) -> bytes: ...
        def to_segments(self) -> list[bytes]: ...
        def as_reader(self) -> Factory.AccessInfoReader: ...
        @staticmethod
        def write(file: BufferedWriter) -> None: ...
        @staticmethod
        def write_packed(file: BufferedWriter) -> None: ...

    class CreateResult(Awaitable[CreateResult], Protocol):
        adminCap: Any
        serviceCaps: Sequence[Identifiable]
        error: str

    def create(
        self,
        timeoutSeconds: int,
        interfaceNameToRegistrySR: Sequence[Pair[str, str]],
        msgPayload: Any,
    ) -> CreateResult: ...
    class CreateRequest(Protocol):
        timeoutSeconds: int
        interfaceNameToRegistrySR: Sequence[Pair[str, str]]
        msgPayload: Any
        def send(self) -> Factory.CreateResult: ...

    def create_request(self) -> CreateRequest: ...
    class ServiceinterfacenamesResult(Awaitable[ServiceinterfacenamesResult], Protocol):
        names: Sequence[str]

    def serviceInterfaceNames(self) -> ServiceinterfacenamesResult: ...
    class ServiceinterfacenamesRequest(Protocol):
        def send(self) -> Factory.ServiceinterfacenamesResult: ...

    def serviceInterfaceNames_request(self) -> ServiceinterfacenamesRequest: ...
    class Server(Identifiable.Server):
        def create(
            self,
            timeoutSeconds: int,
            interfaceNameToRegistrySR: Sequence[Pair[str, str]],
            msgPayload: Any,
            **kwargs,
        ) -> Awaitable[Factory.AccessInfo]: ...
        def serviceInterfaceNames(self, **kwargs) -> Awaitable[Sequence[str]]: ...

class Stoppable(Protocol):
    class StopResult(Awaitable[StopResult], Protocol):
        success: bool

    def stop(self) -> StopResult: ...
    class StopRequest(Protocol):
        def send(self) -> Stoppable.StopResult: ...

    def stop_request(self) -> StopRequest: ...
    class Server:
        def stop(self, **kwargs) -> Awaitable[bool]: ...
