"""This is an automatically generated stub for `soil_params.capnp`."""

from __future__ import annotations

from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from io import BufferedWriter
from typing import Any, BinaryIO, Literal, TypeAlias

SoilCharacteristicDataBuilder: TypeAlias = SoilCharacteristicData.Builder
SoilCharacteristicDataReader: TypeAlias = SoilCharacteristicData.Reader

class SoilCharacteristicData:
    DataBuilder: TypeAlias = Data.Builder
    DataReader: TypeAlias = Data.Reader
    class Data:
        class Reader:
            @property
            def soilType(self) -> str: ...
            @property
            def soilRawDensity(self) -> int: ...
            @property
            def airCapacity(self) -> int: ...
            @property
            def fieldCapacity(self) -> int: ...
            @property
            def nFieldCapacity(self) -> int: ...
            def as_builder(self) -> SoilCharacteristicData.Data.Builder: ...

        class Builder:
            @property
            def soilType(self) -> str: ...
            @soilType.setter
            def soilType(self, value: str) -> None: ...
            @property
            def soilRawDensity(self) -> int: ...
            @soilRawDensity.setter
            def soilRawDensity(self, value: int) -> None: ...
            @property
            def airCapacity(self) -> int: ...
            @airCapacity.setter
            def airCapacity(self, value: int) -> None: ...
            @property
            def fieldCapacity(self) -> int: ...
            @fieldCapacity.setter
            def fieldCapacity(self, value: int) -> None: ...
            @property
            def nFieldCapacity(self) -> int: ...
            @nFieldCapacity.setter
            def nFieldCapacity(self, value: int) -> None: ...
            @staticmethod
            def from_dict(
                dictionary: dict[str, Any],
            ) -> SoilCharacteristicData.Data.Builder: ...
            def copy(self) -> SoilCharacteristicData.Data.Builder: ...
            def to_bytes(self) -> bytes: ...
            def to_bytes_packed(self) -> bytes: ...
            def to_segments(self) -> list[bytes]: ...
            def as_reader(self) -> SoilCharacteristicData.Data.Reader: ...
            @staticmethod
            def write(file: BufferedWriter) -> None: ...
            @staticmethod
            def write_packed(file: BufferedWriter) -> None: ...

        @staticmethod
        @contextmanager
        def from_bytes(
            data: bytes,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> Iterator[SoilCharacteristicData.Data.Reader]: ...
        @staticmethod
        def from_bytes_packed(
            data: bytes,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> SoilCharacteristicData.Data.Reader: ...
        @staticmethod
        def new_message(
            num_first_segment_words: int | None = None,
            allocate_seg_callable: Any = None,
            soilType: str | None = None,
            soilRawDensity: int | None = None,
            airCapacity: int | None = None,
            fieldCapacity: int | None = None,
            nFieldCapacity: int | None = None,
        ) -> SoilCharacteristicData.Data.Builder: ...
        @staticmethod
        def read(
            file: BinaryIO,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> SoilCharacteristicData.Data.Reader: ...
        @staticmethod
        def read_packed(
            file: BinaryIO,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> SoilCharacteristicData.Data.Reader: ...
        def to_dict(self) -> dict[str, Any]: ...

    class Reader:
        @property
        def list(self) -> Sequence[SoilCharacteristicData.Data.Reader]: ...
        def as_builder(self) -> SoilCharacteristicData.Builder: ...

    class Builder:
        @property
        def list(self) -> Sequence[SoilCharacteristicData.Data.Builder]: ...
        @list.setter
        def list(
            self,
            value: Sequence[
                SoilCharacteristicData.Data.Builder | SoilCharacteristicData.Data.Reader
            ]
            | Sequence[dict[str, Any]],
        ) -> None: ...
        @staticmethod
        def from_dict(dictionary: dict[str, Any]) -> SoilCharacteristicData.Builder: ...
        def init(
            self, name: Literal["list"], size: int = ...
        ) -> Sequence[SoilCharacteristicData.Data.Builder]: ...
        def copy(self) -> SoilCharacteristicData.Builder: ...
        def to_bytes(self) -> bytes: ...
        def to_bytes_packed(self) -> bytes: ...
        def to_segments(self) -> list[bytes]: ...
        def as_reader(self) -> SoilCharacteristicData.Reader: ...
        @staticmethod
        def write(file: BufferedWriter) -> None: ...
        @staticmethod
        def write_packed(file: BufferedWriter) -> None: ...

    @staticmethod
    @contextmanager
    def from_bytes(
        data: bytes,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> Iterator[SoilCharacteristicData.Reader]: ...
    @staticmethod
    def from_bytes_packed(
        data: bytes,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> SoilCharacteristicData.Reader: ...
    @staticmethod
    def new_message(
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        list: Sequence[SoilCharacteristicData.Data.Builder]
        | Sequence[dict[str, Any]]
        | None = None,
    ) -> SoilCharacteristicData.Builder: ...
    @staticmethod
    def read(
        file: BinaryIO,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> SoilCharacteristicData.Reader: ...
    @staticmethod
    def read_packed(
        file: BinaryIO,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> SoilCharacteristicData.Reader: ...
    def to_dict(self) -> dict[str, Any]: ...

SoilCharacteristicModifierBuilder: TypeAlias = SoilCharacteristicModifier.Builder
SoilCharacteristicModifierReader: TypeAlias = SoilCharacteristicModifier.Reader

class SoilCharacteristicModifier:
    DataBuilder: TypeAlias = Data.Builder
    DataReader: TypeAlias = Data.Reader
    class Data:
        class Reader:
            @property
            def soilType(self) -> str: ...
            @property
            def organicMatter(self) -> float: ...
            @property
            def airCapacity(self) -> int: ...
            @property
            def fieldCapacity(self) -> int: ...
            @property
            def nFieldCapacity(self) -> int: ...
            def as_builder(self) -> SoilCharacteristicModifier.Data.Builder: ...

        class Builder:
            @property
            def soilType(self) -> str: ...
            @soilType.setter
            def soilType(self, value: str) -> None: ...
            @property
            def organicMatter(self) -> float: ...
            @organicMatter.setter
            def organicMatter(self, value: float) -> None: ...
            @property
            def airCapacity(self) -> int: ...
            @airCapacity.setter
            def airCapacity(self, value: int) -> None: ...
            @property
            def fieldCapacity(self) -> int: ...
            @fieldCapacity.setter
            def fieldCapacity(self, value: int) -> None: ...
            @property
            def nFieldCapacity(self) -> int: ...
            @nFieldCapacity.setter
            def nFieldCapacity(self, value: int) -> None: ...
            @staticmethod
            def from_dict(
                dictionary: dict[str, Any],
            ) -> SoilCharacteristicModifier.Data.Builder: ...
            def copy(self) -> SoilCharacteristicModifier.Data.Builder: ...
            def to_bytes(self) -> bytes: ...
            def to_bytes_packed(self) -> bytes: ...
            def to_segments(self) -> list[bytes]: ...
            def as_reader(self) -> SoilCharacteristicModifier.Data.Reader: ...
            @staticmethod
            def write(file: BufferedWriter) -> None: ...
            @staticmethod
            def write_packed(file: BufferedWriter) -> None: ...

        @staticmethod
        @contextmanager
        def from_bytes(
            data: bytes,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> Iterator[SoilCharacteristicModifier.Data.Reader]: ...
        @staticmethod
        def from_bytes_packed(
            data: bytes,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> SoilCharacteristicModifier.Data.Reader: ...
        @staticmethod
        def new_message(
            num_first_segment_words: int | None = None,
            allocate_seg_callable: Any = None,
            soilType: str | None = None,
            organicMatter: float | None = None,
            airCapacity: int | None = None,
            fieldCapacity: int | None = None,
            nFieldCapacity: int | None = None,
        ) -> SoilCharacteristicModifier.Data.Builder: ...
        @staticmethod
        def read(
            file: BinaryIO,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> SoilCharacteristicModifier.Data.Reader: ...
        @staticmethod
        def read_packed(
            file: BinaryIO,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> SoilCharacteristicModifier.Data.Reader: ...
        def to_dict(self) -> dict[str, Any]: ...

    class Reader:
        @property
        def list(self) -> Sequence[SoilCharacteristicModifier.Data.Reader]: ...
        def as_builder(self) -> SoilCharacteristicModifier.Builder: ...

    class Builder:
        @property
        def list(self) -> Sequence[SoilCharacteristicModifier.Data.Builder]: ...
        @list.setter
        def list(
            self,
            value: Sequence[
                SoilCharacteristicModifier.Data.Builder
                | SoilCharacteristicModifier.Data.Reader
            ]
            | Sequence[dict[str, Any]],
        ) -> None: ...
        @staticmethod
        def from_dict(
            dictionary: dict[str, Any],
        ) -> SoilCharacteristicModifier.Builder: ...
        def init(
            self, name: Literal["list"], size: int = ...
        ) -> Sequence[SoilCharacteristicModifier.Data.Builder]: ...
        def copy(self) -> SoilCharacteristicModifier.Builder: ...
        def to_bytes(self) -> bytes: ...
        def to_bytes_packed(self) -> bytes: ...
        def to_segments(self) -> list[bytes]: ...
        def as_reader(self) -> SoilCharacteristicModifier.Reader: ...
        @staticmethod
        def write(file: BufferedWriter) -> None: ...
        @staticmethod
        def write_packed(file: BufferedWriter) -> None: ...

    @staticmethod
    @contextmanager
    def from_bytes(
        data: bytes,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> Iterator[SoilCharacteristicModifier.Reader]: ...
    @staticmethod
    def from_bytes_packed(
        data: bytes,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> SoilCharacteristicModifier.Reader: ...
    @staticmethod
    def new_message(
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        list: Sequence[SoilCharacteristicModifier.Data.Builder]
        | Sequence[dict[str, Any]]
        | None = None,
    ) -> SoilCharacteristicModifier.Builder: ...
    @staticmethod
    def read(
        file: BinaryIO,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> SoilCharacteristicModifier.Reader: ...
    @staticmethod
    def read_packed(
        file: BinaryIO,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> SoilCharacteristicModifier.Reader: ...
    def to_dict(self) -> dict[str, Any]: ...

CapillaryRiseRateBuilder: TypeAlias = CapillaryRiseRate.Builder
CapillaryRiseRateReader: TypeAlias = CapillaryRiseRate.Reader

class CapillaryRiseRate:
    DataBuilder: TypeAlias = Data.Builder
    DataReader: TypeAlias = Data.Reader
    class Data:
        class Reader:
            @property
            def soilType(self) -> str: ...
            @property
            def distance(self) -> int: ...
            @property
            def rate(self) -> float: ...
            def as_builder(self) -> CapillaryRiseRate.Data.Builder: ...

        class Builder:
            @property
            def soilType(self) -> str: ...
            @soilType.setter
            def soilType(self, value: str) -> None: ...
            @property
            def distance(self) -> int: ...
            @distance.setter
            def distance(self, value: int) -> None: ...
            @property
            def rate(self) -> float: ...
            @rate.setter
            def rate(self, value: float) -> None: ...
            @staticmethod
            def from_dict(
                dictionary: dict[str, Any],
            ) -> CapillaryRiseRate.Data.Builder: ...
            def copy(self) -> CapillaryRiseRate.Data.Builder: ...
            def to_bytes(self) -> bytes: ...
            def to_bytes_packed(self) -> bytes: ...
            def to_segments(self) -> list[bytes]: ...
            def as_reader(self) -> CapillaryRiseRate.Data.Reader: ...
            @staticmethod
            def write(file: BufferedWriter) -> None: ...
            @staticmethod
            def write_packed(file: BufferedWriter) -> None: ...

        @staticmethod
        @contextmanager
        def from_bytes(
            data: bytes,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> Iterator[CapillaryRiseRate.Data.Reader]: ...
        @staticmethod
        def from_bytes_packed(
            data: bytes,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> CapillaryRiseRate.Data.Reader: ...
        @staticmethod
        def new_message(
            num_first_segment_words: int | None = None,
            allocate_seg_callable: Any = None,
            soilType: str | None = None,
            distance: int | None = None,
            rate: float | None = None,
        ) -> CapillaryRiseRate.Data.Builder: ...
        @staticmethod
        def read(
            file: BinaryIO,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> CapillaryRiseRate.Data.Reader: ...
        @staticmethod
        def read_packed(
            file: BinaryIO,
            traversal_limit_in_words: int | None = ...,
            nesting_limit: int | None = ...,
        ) -> CapillaryRiseRate.Data.Reader: ...
        def to_dict(self) -> dict[str, Any]: ...

    class Reader:
        @property
        def list(self) -> Sequence[CapillaryRiseRate.Data.Reader]: ...
        def as_builder(self) -> CapillaryRiseRate.Builder: ...

    class Builder:
        @property
        def list(self) -> Sequence[CapillaryRiseRate.Data.Builder]: ...
        @list.setter
        def list(
            self,
            value: Sequence[
                CapillaryRiseRate.Data.Builder | CapillaryRiseRate.Data.Reader
            ]
            | Sequence[dict[str, Any]],
        ) -> None: ...
        @staticmethod
        def from_dict(dictionary: dict[str, Any]) -> CapillaryRiseRate.Builder: ...
        def init(
            self, name: Literal["list"], size: int = ...
        ) -> Sequence[CapillaryRiseRate.Data.Builder]: ...
        def copy(self) -> CapillaryRiseRate.Builder: ...
        def to_bytes(self) -> bytes: ...
        def to_bytes_packed(self) -> bytes: ...
        def to_segments(self) -> list[bytes]: ...
        def as_reader(self) -> CapillaryRiseRate.Reader: ...
        @staticmethod
        def write(file: BufferedWriter) -> None: ...
        @staticmethod
        def write_packed(file: BufferedWriter) -> None: ...

    @staticmethod
    @contextmanager
    def from_bytes(
        data: bytes,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> Iterator[CapillaryRiseRate.Reader]: ...
    @staticmethod
    def from_bytes_packed(
        data: bytes,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> CapillaryRiseRate.Reader: ...
    @staticmethod
    def new_message(
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        list: Sequence[CapillaryRiseRate.Data.Builder]
        | Sequence[dict[str, Any]]
        | None = None,
    ) -> CapillaryRiseRate.Builder: ...
    @staticmethod
    def read(
        file: BinaryIO,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> CapillaryRiseRate.Reader: ...
    @staticmethod
    def read_packed(
        file: BinaryIO,
        traversal_limit_in_words: int | None = ...,
        nesting_limit: int | None = ...,
    ) -> CapillaryRiseRate.Reader: ...
    def to_dict(self) -> dict[str, Any]: ...
