"""This is an automatically generated stub for `common.capnp`."""

from __future__ import annotations

from collections.abc import Awaitable, Iterator, MutableSequence, Sequence
from enum import Enum
from typing import (
    Any,
    Generic,
    Literal,
    NamedTuple,
    Protocol,
    TypeAlias,
    TypeVar,
    overload,
    override,
)

from capnp.lib.capnp import (
    _DynamicCapabilityClient,
    _DynamicCapabilityServer,
    _DynamicObjectReader,
    _DynamicStructBuilder,
    _DynamicStructReader,
    _InterfaceModule,
    _Request,
    _StructModule,
)

_ValueModule_F = TypeVar("_ValueModule_F")
_ValueModule_S = TypeVar("_ValueModule_S")

class _IdInformationModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def id(self) -> str: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def description(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _IdInformationModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def id(self) -> str: ...
        @id.setter
        def id(self, value: str) -> None: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @name.setter
        def name(self, value: str) -> None: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def description(self) -> str: ...
        @description.setter
        def description(self, value: str) -> None: ...
        @override
        def as_reader(self) -> _IdInformationModule.Reader: ...

    @override
    def new_message(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None, id: str | None = None, name: str | None = None, description: str | None = None) -> _IdInformationModule.Builder: ...

IdInformationReader: TypeAlias = _IdInformationModule.Reader
IdInformationBuilder: TypeAlias = _IdInformationModule.Builder
IdInformation: _IdInformationModule

class _IdentifiableModule(_InterfaceModule):
    class InfoRequest(Protocol):
        def send(self) -> _IdentifiableModule.IdentifiableClient.InfoResult: ...

    @classmethod
    def _new_client(cls, server: _IdentifiableModule.Server) -> _IdentifiableModule.IdentifiableClient: ...
    class Server(_DynamicCapabilityServer):
        class InfoResult(Awaitable[InfoResult], Protocol):
            id: str
            name: str
            description: str

        class InfoResultTuple(NamedTuple):
            id: str
            name: str
            description: str

        class InfoCallContext(Protocol):
            params: _IdentifiableModule.InfoRequest
            results: _IdentifiableModule.Server.InfoResult

        def info(self, _context: _IdentifiableModule.Server.InfoCallContext, **kwargs: Any) -> Awaitable[_IdentifiableModule.Server.InfoResultTuple | None]: ...
        def info_context(self, context: _IdentifiableModule.Server.InfoCallContext) -> Awaitable[None]: ...

    class IdentifiableClient(_DynamicCapabilityClient):
        class InfoResult(Awaitable[InfoResult], Protocol):
            id: str
            name: str
            description: str

        def info(self) -> _IdentifiableModule.IdentifiableClient.InfoResult: ...
        def info_request(self) -> _IdentifiableModule.InfoRequest: ...

Identifiable: _IdentifiableModule
IdentifiableClient: TypeAlias = _IdentifiableModule.IdentifiableClient

class _StructuredTextModule(_StructModule):
    class _TypeModule(Enum):
        unstructured = 0
        json = 1
        xml = 2
        toml = 3
        sturdyRef = 4

    Type: TypeAlias = _TypeModule
    class _StructureModule(_StructModule):
        class Reader(_DynamicStructReader):
            @property
            def none(self) -> None: ...
            @property
            def json(self) -> None: ...
            @property
            def xml(self) -> None: ...
            @property
            def toml(self) -> None: ...
            @override
            def which(self) -> Literal["none", "json", "xml", "toml"]: ...
            @override
            def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _StructuredTextModule._StructureModule.Builder: ...

        class Builder(_DynamicStructBuilder):
            @property
            def none(self) -> None: ...
            @none.setter
            def none(self, value: None) -> None: ...
            @property
            def json(self) -> None: ...
            @json.setter
            def json(self, value: None) -> None: ...
            @property
            def xml(self) -> None: ...
            @xml.setter
            def xml(self, value: None) -> None: ...
            @property
            def toml(self) -> None: ...
            @toml.setter
            def toml(self, value: None) -> None: ...
            @override
            def which(self) -> Literal["none", "json", "xml", "toml"]: ...
            @override
            def as_reader(self) -> _StructuredTextModule._StructureModule.Reader: ...

        @override
        def new_message(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None, none: None | None = None, json: None | None = None, xml: None | None = None, toml: None | None = None) -> _StructuredTextModule._StructureModule.Builder: ...

    StructureReader: TypeAlias = _StructureModule.Reader
    StructureBuilder: TypeAlias = _StructureModule.Builder
    Structure: _StructureModule
    class Reader(_DynamicStructReader):
        @property
        def value(self) -> str: ...
        @property
        def structure(self) -> _StructuredTextModule._StructureModule.Reader: ...
        @property
        def type(self) -> _StructuredTextModule._TypeModule: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _StructuredTextModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def value(self) -> str: ...
        @value.setter
        def value(self, value: str) -> None: ...
        @property
        def structure(self) -> _StructuredTextModule._StructureModule.Builder: ...
        @structure.setter
        def structure(self, value: _StructuredTextModule._StructureModule.Builder | _StructuredTextModule._StructureModule.Reader | dict[str, Any]) -> None: ...
        @property
        def type(self) -> _StructuredTextModule._TypeModule: ...
        @type.setter
        def type(self, value: _StructuredTextModule._TypeModule | Literal["unstructured", "json", "xml", "toml", "sturdyRef"]) -> None: ...
        def init(self, field: Literal["structure"], size: int | None = None) -> _StructuredTextModule._StructureModule.Builder: ...
        @override
        def as_reader(self) -> _StructuredTextModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        value: str | None = None,
        structure: _StructuredTextModule._StructureModule.Builder | dict[str, Any] | None = None,
        type: _StructuredTextModule._TypeModule | Literal["unstructured", "json", "xml", "toml", "sturdyRef"] | None = None,
    ) -> _StructuredTextModule.Builder: ...

StructuredTextReader: TypeAlias = _StructuredTextModule.Reader
StructuredTextBuilder: TypeAlias = _StructuredTextModule.Builder
StructuredText: _StructuredTextModule

class _PairModule(Generic[_ValueModule_F, _ValueModule_S], _StructModule):
    class Reader(_DynamicStructReader):
        @property
        def fst(self) -> _ValueModule_F: ...
        @property
        def snd(self) -> _ValueModule_S: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _PairModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def fst(self) -> _ValueModule_F: ...
        @fst.setter
        def fst(self, value: _ValueModule_F) -> None: ...
        @property
        def snd(self) -> _ValueModule_S: ...
        @snd.setter
        def snd(self, value: _ValueModule_S) -> None: ...
        @override
        def as_reader(self) -> _PairModule.Reader: ...

    @override
    def new_message(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None, fst: _ValueModule_F | None = None, snd: _ValueModule_S | None = None) -> _PairModule.Builder: ...

class _ValueModule(_StructModule):
    PairReader: TypeAlias = _PairModule.Reader
    PairBuilder: TypeAlias = _PairModule.Builder
    Pair: _PairModule
    class Reader(_DynamicStructReader):
        @property
        def f64(self) -> float: ...
        @property
        def f32(self) -> float: ...
        @property
        def i64(self) -> int: ...
        @property
        def i32(self) -> int: ...
        @property
        def i16(self) -> int: ...
        @property
        def i8(self) -> int: ...
        @property
        def ui64(self) -> int: ...
        @property
        def ui32(self) -> int: ...
        @property
        def ui16(self) -> int: ...
        @property
        def ui8(self) -> int: ...
        @property
        def b(self) -> bool: ...
        @property
        def t(self) -> str: ...
        @property
        def d(self) -> bytes: ...
        @property
        def p(self) -> Any: ...
        @property
        def cap(self) -> Any: ...
        @property
        def lf64(self) -> Sequence[float]: ...
        @property
        def lf32(self) -> Sequence[float]: ...
        @property
        def li64(self) -> Sequence[int]: ...
        @property
        def li32(self) -> Sequence[int]: ...
        @property
        def li16(self) -> Sequence[int]: ...
        @property
        def li8(self) -> Sequence[int]: ...
        @property
        def lui64(self) -> Sequence[int]: ...
        @property
        def lui32(self) -> Sequence[int]: ...
        @property
        def lui16(self) -> Sequence[int]: ...
        @property
        def lui8(self) -> Sequence[int]: ...
        @property
        def lb(self) -> Sequence[bool]: ...
        @property
        def lt(self) -> Sequence[str]: ...
        @property
        def ld(self) -> Sequence[bytes]: ...
        @property
        def lcap(self) -> Sequence[_DynamicObjectReader]: ...
        @property
        def lpair(self) -> Sequence[_PairModule.Reader]: ...
        @override
        def which(self) -> Literal["f64", "f32", "i64", "i32", "i16", "i8", "ui64", "ui32", "ui16", "ui8", "b", "t", "d", "p", "cap", "lf64", "lf32", "li64", "li32", "li16", "li8", "lui64", "lui32", "lui16", "lui8", "lb", "lt", "ld", "lcap", "lpair"]: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _ValueModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def f64(self) -> float: ...
        @f64.setter
        def f64(self, value: float) -> None: ...
        @property
        def f32(self) -> float: ...
        @f32.setter
        def f32(self, value: float) -> None: ...
        @property
        def i64(self) -> int: ...
        @i64.setter
        def i64(self, value: int) -> None: ...
        @property
        def i32(self) -> int: ...
        @i32.setter
        def i32(self, value: int) -> None: ...
        @property
        def i16(self) -> int: ...
        @i16.setter
        def i16(self, value: int) -> None: ...
        @property
        def i8(self) -> int: ...
        @i8.setter
        def i8(self, value: int) -> None: ...
        @property
        def ui64(self) -> int: ...
        @ui64.setter
        def ui64(self, value: int) -> None: ...
        @property
        def ui32(self) -> int: ...
        @ui32.setter
        def ui32(self, value: int) -> None: ...
        @property
        def ui16(self) -> int: ...
        @ui16.setter
        def ui16(self, value: int) -> None: ...
        @property
        def ui8(self) -> int: ...
        @ui8.setter
        def ui8(self, value: int) -> None: ...
        @property
        def b(self) -> bool: ...
        @b.setter
        def b(self, value: bool) -> None: ...
        @property
        def t(self) -> str: ...
        @t.setter
        def t(self, value: str) -> None: ...
        @property
        def d(self) -> bytes: ...
        @d.setter
        def d(self, value: bytes) -> None: ...
        @property
        def p(self) -> Any: ...
        @p.setter
        def p(self, value: Any) -> None: ...
        @property
        def cap(self) -> Any: ...
        @cap.setter
        def cap(self, value: Any) -> None: ...
        @property
        def lf64(self) -> MutableSequence[float]: ...
        @lf64.setter
        def lf64(self, value: Sequence[float]) -> None: ...
        @property
        def lf32(self) -> MutableSequence[float]: ...
        @lf32.setter
        def lf32(self, value: Sequence[float]) -> None: ...
        @property
        def li64(self) -> MutableSequence[int]: ...
        @li64.setter
        def li64(self, value: Sequence[int]) -> None: ...
        @property
        def li32(self) -> MutableSequence[int]: ...
        @li32.setter
        def li32(self, value: Sequence[int]) -> None: ...
        @property
        def li16(self) -> MutableSequence[int]: ...
        @li16.setter
        def li16(self, value: Sequence[int]) -> None: ...
        @property
        def li8(self) -> MutableSequence[int]: ...
        @li8.setter
        def li8(self, value: Sequence[int]) -> None: ...
        @property
        def lui64(self) -> MutableSequence[int]: ...
        @lui64.setter
        def lui64(self, value: Sequence[int]) -> None: ...
        @property
        def lui32(self) -> MutableSequence[int]: ...
        @lui32.setter
        def lui32(self, value: Sequence[int]) -> None: ...
        @property
        def lui16(self) -> MutableSequence[int]: ...
        @lui16.setter
        def lui16(self, value: Sequence[int]) -> None: ...
        @property
        def lui8(self) -> MutableSequence[int]: ...
        @lui8.setter
        def lui8(self, value: Sequence[int]) -> None: ...
        @property
        def lb(self) -> MutableSequence[bool]: ...
        @lb.setter
        def lb(self, value: Sequence[bool]) -> None: ...
        @property
        def lt(self) -> MutableSequence[str]: ...
        @lt.setter
        def lt(self, value: Sequence[str]) -> None: ...
        @property
        def ld(self) -> MutableSequence[bytes]: ...
        @ld.setter
        def ld(self, value: Sequence[bytes]) -> None: ...
        @property
        def lcap(self) -> MutableSequence[_DynamicObjectReader]: ...
        @lcap.setter
        def lcap(self, value: Sequence[_DynamicObjectReader]) -> None: ...
        @property
        def lpair(self) -> MutableSequence[_PairModule.Builder]: ...
        @lpair.setter
        def lpair(self, value: Sequence[_PairModule.Builder | _PairModule.Reader] | Sequence[dict[str, Any]]) -> None: ...
        @override
        def which(self) -> Literal["f64", "f32", "i64", "i32", "i16", "i8", "ui64", "ui32", "ui16", "ui8", "b", "t", "d", "p", "cap", "lf64", "lf32", "li64", "li32", "li16", "li8", "lui64", "lui32", "lui16", "lui8", "lb", "lt", "ld", "lcap", "lpair"]: ...
        @overload
        def init(self, field: Literal["lf64"], size: int | None = None) -> MutableSequence[float]: ...
        @overload
        def init(self, field: Literal["lf32"], size: int | None = None) -> MutableSequence[float]: ...
        @overload
        def init(self, field: Literal["li64"], size: int | None = None) -> MutableSequence[int]: ...
        @overload
        def init(self, field: Literal["li32"], size: int | None = None) -> MutableSequence[int]: ...
        @overload
        def init(self, field: Literal["li16"], size: int | None = None) -> MutableSequence[int]: ...
        @overload
        def init(self, field: Literal["li8"], size: int | None = None) -> MutableSequence[int]: ...
        @overload
        def init(self, field: Literal["lui64"], size: int | None = None) -> MutableSequence[int]: ...
        @overload
        def init(self, field: Literal["lui32"], size: int | None = None) -> MutableSequence[int]: ...
        @overload
        def init(self, field: Literal["lui16"], size: int | None = None) -> MutableSequence[int]: ...
        @overload
        def init(self, field: Literal["lui8"], size: int | None = None) -> MutableSequence[int]: ...
        @overload
        def init(self, field: Literal["lb"], size: int | None = None) -> MutableSequence[bool]: ...
        @overload
        def init(self, field: Literal["lt"], size: int | None = None) -> MutableSequence[str]: ...
        @overload
        def init(self, field: Literal["ld"], size: int | None = None) -> MutableSequence[bytes]: ...
        @overload
        def init(self, field: Literal["lcap"], size: int | None = None) -> MutableSequence[_DynamicObjectReader]: ...
        @overload
        def init(self, field: Literal["lpair"], size: int | None = None) -> MutableSequence[_PairModule.Builder]: ...
        @overload
        def init(self, field: str, size: int | None = None) -> Any: ...
        @override
        def as_reader(self) -> _ValueModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        f64: float | None = None,
        f32: float | None = None,
        i64: int | None = None,
        i32: int | None = None,
        i16: int | None = None,
        i8: int | None = None,
        ui64: int | None = None,
        ui32: int | None = None,
        ui16: int | None = None,
        ui8: int | None = None,
        b: bool | None = None,
        t: str | None = None,
        d: bytes | None = None,
        p: Any | None = None,
        cap: Any | None = None,
        lf64: Sequence[float] | None = None,
        lf32: Sequence[float] | None = None,
        li64: Sequence[int] | None = None,
        li32: Sequence[int] | None = None,
        li16: Sequence[int] | None = None,
        li8: Sequence[int] | None = None,
        lui64: Sequence[int] | None = None,
        lui32: Sequence[int] | None = None,
        lui16: Sequence[int] | None = None,
        lui8: Sequence[int] | None = None,
        lb: Sequence[bool] | None = None,
        lt: Sequence[str] | None = None,
        ld: Sequence[bytes] | None = None,
        lcap: Sequence[_DynamicObjectReader] | None = None,
        lpair: Sequence[_PairModule.Builder] | Sequence[dict[str, Any]] | None = None,
    ) -> _ValueModule.Builder: ...

ValueReader: TypeAlias = _ValueModule.Reader
ValueBuilder: TypeAlias = _ValueModule.Builder
Value: _ValueModule

class _HolderModule(_InterfaceModule):
    class ValueRequest(Protocol):
        def send(self) -> _HolderModule.HolderClient.ValueResult: ...

    @classmethod
    def _new_client(cls, server: _HolderModule.Server) -> _HolderModule.HolderClient: ...
    class Server(_DynamicCapabilityServer):
        class ValueResult(Awaitable[ValueResult], Protocol):
            value: str | bytes | _DynamicStructBuilder | _DynamicStructReader | _DynamicCapabilityClient | _DynamicCapabilityServer

        class ValueResultTuple(NamedTuple):
            value: str | bytes | _DynamicStructBuilder | _DynamicStructReader | _DynamicCapabilityClient | _DynamicCapabilityServer

        class ValueCallContext(Protocol):
            params: _HolderModule.ValueRequest
            results: _HolderModule.Server.ValueResult

        def value(self, _context: _HolderModule.Server.ValueCallContext, **kwargs: Any) -> Awaitable[_HolderModule.Server.ValueResultTuple | None]: ...
        def value_context(self, context: _HolderModule.Server.ValueCallContext) -> Awaitable[None]: ...

    class HolderClient(_DynamicCapabilityClient):
        class ValueResult(Awaitable[ValueResult], Protocol):
            value: _DynamicObjectReader

        def value(self) -> _HolderModule.HolderClient.ValueResult: ...
        def value_request(self) -> _HolderModule.ValueRequest: ...

Holder: _HolderModule
HolderClient: TypeAlias = _HolderModule.HolderClient

class _IdentifiableHolderModule(_IdentifiableModule, _HolderModule):
    @classmethod
    def _new_client(cls, server: _IdentifiableHolderModule.Server | _HolderModule.Server | _IdentifiableModule.Server) -> _IdentifiableHolderModule.IdentifiableHolderClient: ...
    class Server(_IdentifiableModule.Server, _HolderModule.Server): ...
    class IdentifiableHolderClient(_IdentifiableModule.IdentifiableClient, _HolderModule.HolderClient): ...

IdentifiableHolder: _IdentifiableHolderModule
IdentifiableHolderClient: TypeAlias = _IdentifiableHolderModule.IdentifiableHolderClient

# Top-level type aliases for use in type annotations
StructureBuilder: TypeAlias = _StructuredTextModule._StructureModule.Builder
StructureReader: TypeAlias = _StructuredTextModule._StructureModule.Reader
