"""This is an automatically generated stub for `field_exp_data.capnp`."""

from __future__ import annotations

from collections.abc import MutableSequence, Sequence
from typing import Any, Literal, TypeAlias, overload, override

from capnp.lib.capnp import (
    _DynamicCapabilityClient,
    _DynamicCapabilityServer,
    _DynamicStructBuilder,
    _DynamicStructReader,
    _InterfaceModule,
    _Request,
    _StructModule,
)

from .climate_capnp import TimeSeries, TimeSeriesClient, _TimeSeriesModule
from .date_capnp import _DateModule
from .soil_capnp import Profile, ProfileClient, _ProfileModule

class _WeatherStationModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def id(self) -> str: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def instituteName(self) -> str: ...
        @property
        def site(self) -> str: ...
        @property
        def country(self) -> str: ...
        @property
        def location2ndLevel(self) -> str: ...
        @property
        def location3rdLevel(self) -> str: ...
        @property
        def latitudeInDecDeg(self) -> float: ...
        @property
        def longitudeInDecDeg(self) -> float: ...
        @property
        def elevationM(self) -> float: ...
        @property
        def yearlyAvgTempInDegC(self) -> float: ...
        @property
        def amplitudeOfMonthlyAvgTempsInDegC(self) -> float: ...
        @property
        def tempSensorHeightInM(self) -> float: ...
        @property
        def refHeightWeatherMeasurementInM(self) -> float: ...
        @property
        def refHeightWindspeedMeasurementInM(self) -> float: ...
        @property
        def annualCO2ConcentrationInPPM(self) -> float: ...
        @property
        def notes(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _WeatherStationModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def id(self) -> str: ...
        @id.setter
        def id(self, value: str) -> None: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @name.setter
        def name(self, value: str) -> None: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def instituteName(self) -> str: ...
        @instituteName.setter
        def instituteName(self, value: str) -> None: ...
        @property
        def site(self) -> str: ...
        @site.setter
        def site(self, value: str) -> None: ...
        @property
        def country(self) -> str: ...
        @country.setter
        def country(self, value: str) -> None: ...
        @property
        def location2ndLevel(self) -> str: ...
        @location2ndLevel.setter
        def location2ndLevel(self, value: str) -> None: ...
        @property
        def location3rdLevel(self) -> str: ...
        @location3rdLevel.setter
        def location3rdLevel(self, value: str) -> None: ...
        @property
        def latitudeInDecDeg(self) -> float: ...
        @latitudeInDecDeg.setter
        def latitudeInDecDeg(self, value: float) -> None: ...
        @property
        def longitudeInDecDeg(self) -> float: ...
        @longitudeInDecDeg.setter
        def longitudeInDecDeg(self, value: float) -> None: ...
        @property
        def elevationM(self) -> float: ...
        @elevationM.setter
        def elevationM(self, value: float) -> None: ...
        @property
        def yearlyAvgTempInDegC(self) -> float: ...
        @yearlyAvgTempInDegC.setter
        def yearlyAvgTempInDegC(self, value: float) -> None: ...
        @property
        def amplitudeOfMonthlyAvgTempsInDegC(self) -> float: ...
        @amplitudeOfMonthlyAvgTempsInDegC.setter
        def amplitudeOfMonthlyAvgTempsInDegC(self, value: float) -> None: ...
        @property
        def tempSensorHeightInM(self) -> float: ...
        @tempSensorHeightInM.setter
        def tempSensorHeightInM(self, value: float) -> None: ...
        @property
        def refHeightWeatherMeasurementInM(self) -> float: ...
        @refHeightWeatherMeasurementInM.setter
        def refHeightWeatherMeasurementInM(self, value: float) -> None: ...
        @property
        def refHeightWindspeedMeasurementInM(self) -> float: ...
        @refHeightWindspeedMeasurementInM.setter
        def refHeightWindspeedMeasurementInM(self, value: float) -> None: ...
        @property
        def annualCO2ConcentrationInPPM(self) -> float: ...
        @annualCO2ConcentrationInPPM.setter
        def annualCO2ConcentrationInPPM(self, value: float) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @override
        def as_reader(self) -> _WeatherStationModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        id: str | None = None,
        name: str | None = None,
        instituteName: str | None = None,
        site: str | None = None,
        country: str | None = None,
        location2ndLevel: str | None = None,
        location3rdLevel: str | None = None,
        latitudeInDecDeg: float | None = None,
        longitudeInDecDeg: float | None = None,
        elevationM: float | None = None,
        yearlyAvgTempInDegC: float | None = None,
        amplitudeOfMonthlyAvgTempsInDegC: float | None = None,
        tempSensorHeightInM: float | None = None,
        refHeightWeatherMeasurementInM: float | None = None,
        refHeightWindspeedMeasurementInM: float | None = None,
        annualCO2ConcentrationInPPM: float | None = None,
        notes: str | None = None,
    ) -> _WeatherStationModule.Builder: ...

WeatherStationReader: TypeAlias = _WeatherStationModule.Reader
WeatherStationBuilder: TypeAlias = _WeatherStationModule.Builder
WeatherStation: _WeatherStationModule

class _SoilMetadataModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def id(self) -> str: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def source(self) -> str: ...
        @property
        def depthInCM(self) -> int: ...
        @property
        def obstableDepthInCM(self) -> int: ...
        @property
        def depthOfTopsoilInCM(self) -> int: ...
        @property
        def drainageRatePerDay(self) -> float: ...
        @property
        def runoffCureNoSCS(self) -> float: ...
        @property
        def soilAvailableWaterContentInCM(self) -> float: ...
        @property
        def surfaceStoneCoverAsFraction(self) -> float: ...
        @property
        def soilAlbedo(self) -> float: ...
        @property
        def soilEvaporationLimitInMM(self) -> float: ...
        @property
        def mineralizationFactor(self) -> float: ...
        @property
        def soilFertilityOnFoto(self) -> float: ...
        @property
        def soilClassificationSystem(self) -> str: ...
        @property
        def soilTexture(self) -> str: ...
        @property
        def classification(self) -> str: ...
        @property
        def notes(self) -> str: ...
        @property
        def profile(self) -> _ProfileModule.ProfileClient: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _SoilMetadataModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def id(self) -> str: ...
        @id.setter
        def id(self, value: str) -> None: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @name.setter
        def name(self, value: str) -> None: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def source(self) -> str: ...
        @source.setter
        def source(self, value: str) -> None: ...
        @property
        def depthInCM(self) -> int: ...
        @depthInCM.setter
        def depthInCM(self, value: int) -> None: ...
        @property
        def obstableDepthInCM(self) -> int: ...
        @obstableDepthInCM.setter
        def obstableDepthInCM(self, value: int) -> None: ...
        @property
        def depthOfTopsoilInCM(self) -> int: ...
        @depthOfTopsoilInCM.setter
        def depthOfTopsoilInCM(self, value: int) -> None: ...
        @property
        def drainageRatePerDay(self) -> float: ...
        @drainageRatePerDay.setter
        def drainageRatePerDay(self, value: float) -> None: ...
        @property
        def runoffCureNoSCS(self) -> float: ...
        @runoffCureNoSCS.setter
        def runoffCureNoSCS(self, value: float) -> None: ...
        @property
        def soilAvailableWaterContentInCM(self) -> float: ...
        @soilAvailableWaterContentInCM.setter
        def soilAvailableWaterContentInCM(self, value: float) -> None: ...
        @property
        def surfaceStoneCoverAsFraction(self) -> float: ...
        @surfaceStoneCoverAsFraction.setter
        def surfaceStoneCoverAsFraction(self, value: float) -> None: ...
        @property
        def soilAlbedo(self) -> float: ...
        @soilAlbedo.setter
        def soilAlbedo(self, value: float) -> None: ...
        @property
        def soilEvaporationLimitInMM(self) -> float: ...
        @soilEvaporationLimitInMM.setter
        def soilEvaporationLimitInMM(self, value: float) -> None: ...
        @property
        def mineralizationFactor(self) -> float: ...
        @mineralizationFactor.setter
        def mineralizationFactor(self, value: float) -> None: ...
        @property
        def soilFertilityOnFoto(self) -> float: ...
        @soilFertilityOnFoto.setter
        def soilFertilityOnFoto(self, value: float) -> None: ...
        @property
        def soilClassificationSystem(self) -> str: ...
        @soilClassificationSystem.setter
        def soilClassificationSystem(self, value: str) -> None: ...
        @property
        def soilTexture(self) -> str: ...
        @soilTexture.setter
        def soilTexture(self, value: str) -> None: ...
        @property
        def classification(self) -> str: ...
        @classification.setter
        def classification(self, value: str) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @property
        def profile(self) -> _ProfileModule.ProfileClient: ...
        @profile.setter
        def profile(self, value: _ProfileModule.ProfileClient | _ProfileModule.Server) -> None: ...
        @override
        def as_reader(self) -> _SoilMetadataModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        id: str | None = None,
        name: str | None = None,
        source: str | None = None,
        depthInCM: int | None = None,
        obstableDepthInCM: int | None = None,
        depthOfTopsoilInCM: int | None = None,
        drainageRatePerDay: float | None = None,
        runoffCureNoSCS: float | None = None,
        soilAvailableWaterContentInCM: float | None = None,
        surfaceStoneCoverAsFraction: float | None = None,
        soilAlbedo: float | None = None,
        soilEvaporationLimitInMM: float | None = None,
        mineralizationFactor: float | None = None,
        soilFertilityOnFoto: float | None = None,
        soilClassificationSystem: str | None = None,
        soilTexture: str | None = None,
        classification: str | None = None,
        notes: str | None = None,
        profile: _ProfileModule.ProfileClient | _ProfileModule.Server | None = None,
    ) -> _SoilMetadataModule.Builder: ...

SoilMetadataReader: TypeAlias = _SoilMetadataModule.Reader
SoilMetadataBuilder: TypeAlias = _SoilMetadataModule.Builder
SoilMetadata: _SoilMetadataModule

class _FieldModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def id(self) -> str: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def latitudeInDecDeg(self) -> float: ...
        @property
        def longitudeInDecDeg(self) -> float: ...
        @property
        def elevationInM(self) -> float: ...
        @property
        def slopeDegreeInDeg(self) -> float: ...
        @property
        def drainageType(self) -> str: ...
        @property
        def distanceToWeatherStationInKM(self) -> float: ...
        @property
        def country(self) -> str: ...
        @property
        def subCountry(self) -> str: ...
        @property
        def subSubCountry(self) -> str: ...
        @property
        def notes(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _FieldModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def id(self) -> str: ...
        @id.setter
        def id(self, value: str) -> None: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @name.setter
        def name(self, value: str) -> None: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def latitudeInDecDeg(self) -> float: ...
        @latitudeInDecDeg.setter
        def latitudeInDecDeg(self, value: float) -> None: ...
        @property
        def longitudeInDecDeg(self) -> float: ...
        @longitudeInDecDeg.setter
        def longitudeInDecDeg(self, value: float) -> None: ...
        @property
        def elevationInM(self) -> float: ...
        @elevationInM.setter
        def elevationInM(self, value: float) -> None: ...
        @property
        def slopeDegreeInDeg(self) -> float: ...
        @slopeDegreeInDeg.setter
        def slopeDegreeInDeg(self, value: float) -> None: ...
        @property
        def drainageType(self) -> str: ...
        @drainageType.setter
        def drainageType(self, value: str) -> None: ...
        @property
        def distanceToWeatherStationInKM(self) -> float: ...
        @distanceToWeatherStationInKM.setter
        def distanceToWeatherStationInKM(self, value: float) -> None: ...
        @property
        def country(self) -> str: ...
        @country.setter
        def country(self, value: str) -> None: ...
        @property
        def subCountry(self) -> str: ...
        @subCountry.setter
        def subCountry(self, value: str) -> None: ...
        @property
        def subSubCountry(self) -> str: ...
        @subSubCountry.setter
        def subSubCountry(self, value: str) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @override
        def as_reader(self) -> _FieldModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        id: str | None = None,
        name: str | None = None,
        latitudeInDecDeg: float | None = None,
        longitudeInDecDeg: float | None = None,
        elevationInM: float | None = None,
        slopeDegreeInDeg: float | None = None,
        drainageType: str | None = None,
        distanceToWeatherStationInKM: float | None = None,
        country: str | None = None,
        subCountry: str | None = None,
        subSubCountry: str | None = None,
        notes: str | None = None,
    ) -> _FieldModule.Builder: ...

FieldReader: TypeAlias = _FieldModule.Reader
FieldBuilder: TypeAlias = _FieldModule.Builder
Field: _FieldModule

class _CultivarModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def id(self) -> str: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def accessionId(self) -> str: ...
        @property
        def accessionLocation(self) -> str: ...
        @property
        def cropIdentifierICASA(self) -> str: ...
        @property
        def seedLot(self) -> str: ...
        @property
        def breedingProgram(self) -> str: ...
        @property
        def originalName(self) -> str: ...
        @property
        def releaseYear(self) -> int: ...
        @property
        def synonym(self) -> str: ...
        @property
        def notes(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _CultivarModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def id(self) -> str: ...
        @id.setter
        def id(self, value: str) -> None: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @name.setter
        def name(self, value: str) -> None: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def accessionId(self) -> str: ...
        @accessionId.setter
        def accessionId(self, value: str) -> None: ...
        @property
        def accessionLocation(self) -> str: ...
        @accessionLocation.setter
        def accessionLocation(self, value: str) -> None: ...
        @property
        def cropIdentifierICASA(self) -> str: ...
        @cropIdentifierICASA.setter
        def cropIdentifierICASA(self, value: str) -> None: ...
        @property
        def seedLot(self) -> str: ...
        @seedLot.setter
        def seedLot(self, value: str) -> None: ...
        @property
        def breedingProgram(self) -> str: ...
        @breedingProgram.setter
        def breedingProgram(self, value: str) -> None: ...
        @property
        def originalName(self) -> str: ...
        @originalName.setter
        def originalName(self, value: str) -> None: ...
        @property
        def releaseYear(self) -> int: ...
        @releaseYear.setter
        def releaseYear(self, value: int) -> None: ...
        @property
        def synonym(self) -> str: ...
        @synonym.setter
        def synonym(self, value: str) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @override
        def as_reader(self) -> _CultivarModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        id: str | None = None,
        name: str | None = None,
        accessionId: str | None = None,
        accessionLocation: str | None = None,
        cropIdentifierICASA: str | None = None,
        seedLot: str | None = None,
        breedingProgram: str | None = None,
        originalName: str | None = None,
        releaseYear: int | None = None,
        synonym: str | None = None,
        notes: str | None = None,
    ) -> _CultivarModule.Builder: ...

class _PlotModule(_StructModule):
    CultivarReader: TypeAlias = _CultivarModule.Reader
    CultivarBuilder: TypeAlias = _CultivarModule.Builder
    Cultivar: _CultivarModule
    class Reader(_DynamicStructReader):
        @property
        def id(self) -> str: ...
        @property
        def cultivar(self) -> _CultivarModule.Reader: ...
        @property
        def soil(self) -> _SoilMetadataModule.Reader: ...
        @property
        def blockNumber(self) -> int: ...
        @property
        def plotNumber(self) -> int: ...
        @property
        def replicateNumber(self) -> int: ...
        @property
        def rowNumber(self) -> int: ...
        @property
        def columnNumber(self) -> int: ...
        @property
        def harvestMethod(self) -> str: ...
        @property
        def notes(self) -> str: ...
        @property
        def experimentId(self) -> str: ...
        @property
        def treatmentId(self) -> str: ...
        @property
        def cultivarId(self) -> str: ...
        @property
        def soilId(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _PlotModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def id(self) -> str: ...
        @id.setter
        def id(self, value: str) -> None: ...
        @property
        def cultivar(self) -> _CultivarModule.Builder: ...
        @cultivar.setter
        def cultivar(self, value: _CultivarModule.Builder | _CultivarModule.Reader | dict[str, Any]) -> None: ...
        @property
        def soil(self) -> _SoilMetadataModule.Builder: ...
        @soil.setter
        def soil(self, value: _SoilMetadataModule.Builder | _SoilMetadataModule.Reader | dict[str, Any]) -> None: ...
        @property
        def blockNumber(self) -> int: ...
        @blockNumber.setter
        def blockNumber(self, value: int) -> None: ...
        @property
        def plotNumber(self) -> int: ...
        @plotNumber.setter
        def plotNumber(self, value: int) -> None: ...
        @property
        def replicateNumber(self) -> int: ...
        @replicateNumber.setter
        def replicateNumber(self, value: int) -> None: ...
        @property
        def rowNumber(self) -> int: ...
        @rowNumber.setter
        def rowNumber(self, value: int) -> None: ...
        @property
        def columnNumber(self) -> int: ...
        @columnNumber.setter
        def columnNumber(self, value: int) -> None: ...
        @property
        def harvestMethod(self) -> str: ...
        @harvestMethod.setter
        def harvestMethod(self, value: str) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @property
        def experimentId(self) -> str: ...
        @experimentId.setter
        def experimentId(self, value: str) -> None: ...
        @property
        def treatmentId(self) -> str: ...
        @treatmentId.setter
        def treatmentId(self, value: str) -> None: ...
        @property
        def cultivarId(self) -> str: ...
        @cultivarId.setter
        def cultivarId(self, value: str) -> None: ...
        @property
        def soilId(self) -> str: ...
        @soilId.setter
        def soilId(self, value: str) -> None: ...
        @overload
        def init(self, field: Literal["cultivar"], size: int | None = None) -> _CultivarModule.Builder: ...
        @overload
        def init(self, field: Literal["soil"], size: int | None = None) -> _SoilMetadataModule.Builder: ...
        @overload
        def init(self, field: str, size: int | None = None) -> Any: ...
        @override
        def as_reader(self) -> _PlotModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        id: str | None = None,
        cultivar: _CultivarModule.Builder | dict[str, Any] | None = None,
        soil: _SoilMetadataModule.Builder | dict[str, Any] | None = None,
        blockNumber: int | None = None,
        plotNumber: int | None = None,
        replicateNumber: int | None = None,
        rowNumber: int | None = None,
        columnNumber: int | None = None,
        harvestMethod: str | None = None,
        notes: str | None = None,
        experimentId: str | None = None,
        treatmentId: str | None = None,
        cultivarId: str | None = None,
        soilId: str | None = None,
    ) -> _PlotModule.Builder: ...

class _ResidueModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def initialMeasureDate(self) -> _DateModule.Reader: ...
        @property
        def incorporationDepth(self) -> int: ...
        @property
        def percentIncorporated(self) -> float: ...
        @property
        def prevCropCode(self) -> str: ...
        @property
        def aboveGroundWeight(self) -> float: ...
        @property
        def aboveGroundNConcentrationInPerc(self) -> float: ...
        @property
        def rootWeightPreviousCrop(self) -> float: ...
        @property
        def experimentId(self) -> str: ...
        @property
        def treatmentId(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _ResidueModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def initialMeasureDate(self) -> _DateModule.Builder: ...
        @initialMeasureDate.setter
        def initialMeasureDate(self, value: _DateModule.Builder | _DateModule.Reader | dict[str, Any]) -> None: ...
        @property
        def incorporationDepth(self) -> int: ...
        @incorporationDepth.setter
        def incorporationDepth(self, value: int) -> None: ...
        @property
        def percentIncorporated(self) -> float: ...
        @percentIncorporated.setter
        def percentIncorporated(self, value: float) -> None: ...
        @property
        def prevCropCode(self) -> str: ...
        @prevCropCode.setter
        def prevCropCode(self, value: str) -> None: ...
        @property
        def aboveGroundWeight(self) -> float: ...
        @aboveGroundWeight.setter
        def aboveGroundWeight(self, value: float) -> None: ...
        @property
        def aboveGroundNConcentrationInPerc(self) -> float: ...
        @aboveGroundNConcentrationInPerc.setter
        def aboveGroundNConcentrationInPerc(self, value: float) -> None: ...
        @property
        def rootWeightPreviousCrop(self) -> float: ...
        @rootWeightPreviousCrop.setter
        def rootWeightPreviousCrop(self, value: float) -> None: ...
        @property
        def experimentId(self) -> str: ...
        @experimentId.setter
        def experimentId(self, value: str) -> None: ...
        @property
        def treatmentId(self) -> str: ...
        @treatmentId.setter
        def treatmentId(self, value: str) -> None: ...
        def init(self, field: Literal["initialMeasureDate"], size: int | None = None) -> _DateModule.Builder: ...
        @override
        def as_reader(self) -> _ResidueModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        initialMeasureDate: _DateModule.Builder | dict[str, Any] | None = None,
        incorporationDepth: int | None = None,
        percentIncorporated: float | None = None,
        prevCropCode: str | None = None,
        aboveGroundWeight: float | None = None,
        aboveGroundNConcentrationInPerc: float | None = None,
        rootWeightPreviousCrop: float | None = None,
        experimentId: str | None = None,
        treatmentId: str | None = None,
    ) -> _ResidueModule.Builder: ...

class _InitialConditionsLayerModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def date(self) -> _DateModule.Reader: ...
        @property
        def soilLayerTopDepthInCM(self) -> int: ...
        @property
        def soilLayerBaseDepthInCM(self) -> int: ...
        @property
        def waterConcentration(self) -> float: ...
        @property
        def totalNInKGperHA(self) -> float: ...
        @property
        def massNH4InKGperHA(self) -> float: ...
        @property
        def massNO3InKGperHA(self) -> float: ...
        @property
        def concNH4InPPM(self) -> float: ...
        @property
        def concNO3InPPM(self) -> float: ...
        @property
        def experimentId(self) -> str: ...
        @property
        def treatmentId(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _InitialConditionsLayerModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def date(self) -> _DateModule.Builder: ...
        @date.setter
        def date(self, value: _DateModule.Builder | _DateModule.Reader | dict[str, Any]) -> None: ...
        @property
        def soilLayerTopDepthInCM(self) -> int: ...
        @soilLayerTopDepthInCM.setter
        def soilLayerTopDepthInCM(self, value: int) -> None: ...
        @property
        def soilLayerBaseDepthInCM(self) -> int: ...
        @soilLayerBaseDepthInCM.setter
        def soilLayerBaseDepthInCM(self, value: int) -> None: ...
        @property
        def waterConcentration(self) -> float: ...
        @waterConcentration.setter
        def waterConcentration(self, value: float) -> None: ...
        @property
        def totalNInKGperHA(self) -> float: ...
        @totalNInKGperHA.setter
        def totalNInKGperHA(self, value: float) -> None: ...
        @property
        def massNH4InKGperHA(self) -> float: ...
        @massNH4InKGperHA.setter
        def massNH4InKGperHA(self, value: float) -> None: ...
        @property
        def massNO3InKGperHA(self) -> float: ...
        @massNO3InKGperHA.setter
        def massNO3InKGperHA(self, value: float) -> None: ...
        @property
        def concNH4InPPM(self) -> float: ...
        @concNH4InPPM.setter
        def concNH4InPPM(self, value: float) -> None: ...
        @property
        def concNO3InPPM(self) -> float: ...
        @concNO3InPPM.setter
        def concNO3InPPM(self, value: float) -> None: ...
        @property
        def experimentId(self) -> str: ...
        @experimentId.setter
        def experimentId(self, value: str) -> None: ...
        @property
        def treatmentId(self) -> str: ...
        @treatmentId.setter
        def treatmentId(self, value: str) -> None: ...
        def init(self, field: Literal["date"], size: int | None = None) -> _DateModule.Builder: ...
        @override
        def as_reader(self) -> _InitialConditionsLayerModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        date: _DateModule.Builder | dict[str, Any] | None = None,
        soilLayerTopDepthInCM: int | None = None,
        soilLayerBaseDepthInCM: int | None = None,
        waterConcentration: float | None = None,
        totalNInKGperHA: float | None = None,
        massNH4InKGperHA: float | None = None,
        massNO3InKGperHA: float | None = None,
        concNH4InPPM: float | None = None,
        concNO3InPPM: float | None = None,
        experimentId: str | None = None,
        treatmentId: str | None = None,
    ) -> _InitialConditionsLayerModule.Builder: ...

class _PlantingEventModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def plantingDistribution(self) -> str: ...
        @property
        def rowSpacingInCM(self) -> float: ...
        @property
        def rowDirectionInArcDeg(self) -> float: ...
        @property
        def plantingDepthInMM(self) -> int: ...
        @property
        def plotLayout(self) -> str: ...
        @property
        def plantingDate(self) -> _DateModule.Reader: ...
        @property
        def plantPopulationAtPlantingInNoPerM2(self) -> int: ...
        @property
        def averageEmergenceDate(self) -> _DateModule.Reader: ...
        @property
        def averagePlantPopulationAtEmergenceInNoPerM2(self) -> int: ...
        @property
        def notes(self) -> str: ...
        @property
        def experimentId(self) -> str: ...
        @property
        def treatmentId(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _PlantingEventModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def plantingDistribution(self) -> str: ...
        @plantingDistribution.setter
        def plantingDistribution(self, value: str) -> None: ...
        @property
        def rowSpacingInCM(self) -> float: ...
        @rowSpacingInCM.setter
        def rowSpacingInCM(self, value: float) -> None: ...
        @property
        def rowDirectionInArcDeg(self) -> float: ...
        @rowDirectionInArcDeg.setter
        def rowDirectionInArcDeg(self, value: float) -> None: ...
        @property
        def plantingDepthInMM(self) -> int: ...
        @plantingDepthInMM.setter
        def plantingDepthInMM(self, value: int) -> None: ...
        @property
        def plotLayout(self) -> str: ...
        @plotLayout.setter
        def plotLayout(self, value: str) -> None: ...
        @property
        def plantingDate(self) -> _DateModule.Builder: ...
        @plantingDate.setter
        def plantingDate(self, value: _DateModule.Builder | _DateModule.Reader | dict[str, Any]) -> None: ...
        @property
        def plantPopulationAtPlantingInNoPerM2(self) -> int: ...
        @plantPopulationAtPlantingInNoPerM2.setter
        def plantPopulationAtPlantingInNoPerM2(self, value: int) -> None: ...
        @property
        def averageEmergenceDate(self) -> _DateModule.Builder: ...
        @averageEmergenceDate.setter
        def averageEmergenceDate(self, value: _DateModule.Builder | _DateModule.Reader | dict[str, Any]) -> None: ...
        @property
        def averagePlantPopulationAtEmergenceInNoPerM2(self) -> int: ...
        @averagePlantPopulationAtEmergenceInNoPerM2.setter
        def averagePlantPopulationAtEmergenceInNoPerM2(self, value: int) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @property
        def experimentId(self) -> str: ...
        @experimentId.setter
        def experimentId(self, value: str) -> None: ...
        @property
        def treatmentId(self) -> str: ...
        @treatmentId.setter
        def treatmentId(self, value: str) -> None: ...
        @overload
        def init(self, field: Literal["plantingDate"], size: int | None = None) -> _DateModule.Builder: ...
        @overload
        def init(self, field: Literal["averageEmergenceDate"], size: int | None = None) -> _DateModule.Builder: ...
        @overload
        def init(self, field: str, size: int | None = None) -> Any: ...
        @override
        def as_reader(self) -> _PlantingEventModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        plantingDistribution: str | None = None,
        rowSpacingInCM: float | None = None,
        rowDirectionInArcDeg: float | None = None,
        plantingDepthInMM: int | None = None,
        plotLayout: str | None = None,
        plantingDate: _DateModule.Builder | dict[str, Any] | None = None,
        plantPopulationAtPlantingInNoPerM2: int | None = None,
        averageEmergenceDate: _DateModule.Builder | dict[str, Any] | None = None,
        averagePlantPopulationAtEmergenceInNoPerM2: int | None = None,
        notes: str | None = None,
        experimentId: str | None = None,
        treatmentId: str | None = None,
    ) -> _PlantingEventModule.Builder: ...

class _HarvestEventModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def date(self) -> _DateModule.Reader: ...
        @property
        def harvestMethod(self) -> str: ...
        @property
        def harvestArea(self) -> float: ...
        @property
        def notes(self) -> str: ...
        @property
        def comments(self) -> str: ...
        @property
        def experimentId(self) -> str: ...
        @property
        def treatmentId(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _HarvestEventModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def date(self) -> _DateModule.Builder: ...
        @date.setter
        def date(self, value: _DateModule.Builder | _DateModule.Reader | dict[str, Any]) -> None: ...
        @property
        def harvestMethod(self) -> str: ...
        @harvestMethod.setter
        def harvestMethod(self, value: str) -> None: ...
        @property
        def harvestArea(self) -> float: ...
        @harvestArea.setter
        def harvestArea(self, value: float) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @property
        def comments(self) -> str: ...
        @comments.setter
        def comments(self, value: str) -> None: ...
        @property
        def experimentId(self) -> str: ...
        @experimentId.setter
        def experimentId(self, value: str) -> None: ...
        @property
        def treatmentId(self) -> str: ...
        @treatmentId.setter
        def treatmentId(self, value: str) -> None: ...
        def init(self, field: Literal["date"], size: int | None = None) -> _DateModule.Builder: ...
        @override
        def as_reader(self) -> _HarvestEventModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        date: _DateModule.Builder | dict[str, Any] | None = None,
        harvestMethod: str | None = None,
        harvestArea: float | None = None,
        notes: str | None = None,
        comments: str | None = None,
        experimentId: str | None = None,
        treatmentId: str | None = None,
    ) -> _HarvestEventModule.Builder: ...

class _IrrigationEventModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def date(self) -> _DateModule.Reader: ...
        @property
        def operation(self) -> str: ...
        @property
        def applicationDepth(self) -> int: ...
        @property
        def amount(self) -> int: ...
        @property
        def waterNConcentrationInPerc(self) -> float: ...
        @property
        def notes(self) -> str: ...
        @property
        def experimentId(self) -> str: ...
        @property
        def treatmentId(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _IrrigationEventModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def date(self) -> _DateModule.Builder: ...
        @date.setter
        def date(self, value: _DateModule.Builder | _DateModule.Reader | dict[str, Any]) -> None: ...
        @property
        def operation(self) -> str: ...
        @operation.setter
        def operation(self, value: str) -> None: ...
        @property
        def applicationDepth(self) -> int: ...
        @applicationDepth.setter
        def applicationDepth(self, value: int) -> None: ...
        @property
        def amount(self) -> int: ...
        @amount.setter
        def amount(self, value: int) -> None: ...
        @property
        def waterNConcentrationInPerc(self) -> float: ...
        @waterNConcentrationInPerc.setter
        def waterNConcentrationInPerc(self, value: float) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @property
        def experimentId(self) -> str: ...
        @experimentId.setter
        def experimentId(self, value: str) -> None: ...
        @property
        def treatmentId(self) -> str: ...
        @treatmentId.setter
        def treatmentId(self, value: str) -> None: ...
        def init(self, field: Literal["date"], size: int | None = None) -> _DateModule.Builder: ...
        @override
        def as_reader(self) -> _IrrigationEventModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        date: _DateModule.Builder | dict[str, Any] | None = None,
        operation: str | None = None,
        applicationDepth: int | None = None,
        amount: int | None = None,
        waterNConcentrationInPerc: float | None = None,
        notes: str | None = None,
        experimentId: str | None = None,
        treatmentId: str | None = None,
    ) -> _IrrigationEventModule.Builder: ...

class _FertilizerEventModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def date(self) -> _DateModule.Reader: ...
        @property
        def applicationMethod(self) -> str: ...
        @property
        def applicationDepthInCM(self) -> int: ...
        @property
        def material(self) -> str: ...
        @property
        def appliedNInKGNPerHA(self) -> int: ...
        @property
        def appliedNO3InKGNperHA(self) -> int: ...
        @property
        def appliedNH4InKGNperHA(self) -> int: ...
        @property
        def notes(self) -> str: ...
        @property
        def experimentId(self) -> str: ...
        @property
        def treatmentId(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _FertilizerEventModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def date(self) -> _DateModule.Builder: ...
        @date.setter
        def date(self, value: _DateModule.Builder | _DateModule.Reader | dict[str, Any]) -> None: ...
        @property
        def applicationMethod(self) -> str: ...
        @applicationMethod.setter
        def applicationMethod(self, value: str) -> None: ...
        @property
        def applicationDepthInCM(self) -> int: ...
        @applicationDepthInCM.setter
        def applicationDepthInCM(self, value: int) -> None: ...
        @property
        def material(self) -> str: ...
        @material.setter
        def material(self, value: str) -> None: ...
        @property
        def appliedNInKGNPerHA(self) -> int: ...
        @appliedNInKGNPerHA.setter
        def appliedNInKGNPerHA(self, value: int) -> None: ...
        @property
        def appliedNO3InKGNperHA(self) -> int: ...
        @appliedNO3InKGNperHA.setter
        def appliedNO3InKGNperHA(self, value: int) -> None: ...
        @property
        def appliedNH4InKGNperHA(self) -> int: ...
        @appliedNH4InKGNperHA.setter
        def appliedNH4InKGNperHA(self, value: int) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @property
        def experimentId(self) -> str: ...
        @experimentId.setter
        def experimentId(self, value: str) -> None: ...
        @property
        def treatmentId(self) -> str: ...
        @treatmentId.setter
        def treatmentId(self, value: str) -> None: ...
        def init(self, field: Literal["date"], size: int | None = None) -> _DateModule.Builder: ...
        @override
        def as_reader(self) -> _FertilizerEventModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        date: _DateModule.Builder | dict[str, Any] | None = None,
        applicationMethod: str | None = None,
        applicationDepthInCM: int | None = None,
        material: str | None = None,
        appliedNInKGNPerHA: int | None = None,
        appliedNO3InKGNperHA: int | None = None,
        appliedNH4InKGNperHA: int | None = None,
        notes: str | None = None,
        experimentId: str | None = None,
        treatmentId: str | None = None,
    ) -> _FertilizerEventModule.Builder: ...

class _EnvironmentModificationModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def date(self) -> _DateModule.Reader: ...
        @property
        def codeCO2(self) -> str: ...
        @property
        def valueCO2(self) -> int: ...
        @property
        def notes(self) -> str: ...
        @property
        def experimentId(self) -> str: ...
        @property
        def treatmentId(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _EnvironmentModificationModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def date(self) -> _DateModule.Builder: ...
        @date.setter
        def date(self, value: _DateModule.Builder | _DateModule.Reader | dict[str, Any]) -> None: ...
        @property
        def codeCO2(self) -> str: ...
        @codeCO2.setter
        def codeCO2(self, value: str) -> None: ...
        @property
        def valueCO2(self) -> int: ...
        @valueCO2.setter
        def valueCO2(self, value: int) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @property
        def experimentId(self) -> str: ...
        @experimentId.setter
        def experimentId(self, value: str) -> None: ...
        @property
        def treatmentId(self) -> str: ...
        @treatmentId.setter
        def treatmentId(self, value: str) -> None: ...
        def init(self, field: Literal["date"], size: int | None = None) -> _DateModule.Builder: ...
        @override
        def as_reader(self) -> _EnvironmentModificationModule.Reader: ...

    @override
    def new_message(
        self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None, date: _DateModule.Builder | dict[str, Any] | None = None, codeCO2: str | None = None, valueCO2: int | None = None, notes: str | None = None, experimentId: str | None = None, treatmentId: str | None = None
    ) -> _EnvironmentModificationModule.Builder: ...

class _TreatmentModule(_StructModule):
    PlotReader: TypeAlias = _PlotModule.Reader
    PlotBuilder: TypeAlias = _PlotModule.Builder
    Plot: _PlotModule
    ResidueReader: TypeAlias = _ResidueModule.Reader
    ResidueBuilder: TypeAlias = _ResidueModule.Builder
    Residue: _ResidueModule
    InitialConditionsLayerReader: TypeAlias = _InitialConditionsLayerModule.Reader
    InitialConditionsLayerBuilder: TypeAlias = _InitialConditionsLayerModule.Builder
    InitialConditionsLayer: _InitialConditionsLayerModule
    PlantingEventReader: TypeAlias = _PlantingEventModule.Reader
    PlantingEventBuilder: TypeAlias = _PlantingEventModule.Builder
    PlantingEvent: _PlantingEventModule
    HarvestEventReader: TypeAlias = _HarvestEventModule.Reader
    HarvestEventBuilder: TypeAlias = _HarvestEventModule.Builder
    HarvestEvent: _HarvestEventModule
    IrrigationEventReader: TypeAlias = _IrrigationEventModule.Reader
    IrrigationEventBuilder: TypeAlias = _IrrigationEventModule.Builder
    IrrigationEvent: _IrrigationEventModule
    FertilizerEventReader: TypeAlias = _FertilizerEventModule.Reader
    FertilizerEventBuilder: TypeAlias = _FertilizerEventModule.Builder
    FertilizerEvent: _FertilizerEventModule
    EnvironmentModificationReader: TypeAlias = _EnvironmentModificationModule.Reader
    EnvironmentModificationBuilder: TypeAlias = _EnvironmentModificationModule.Builder
    EnvironmentModification: _EnvironmentModificationModule
    class Reader(_DynamicStructReader):
        @property
        def id(self) -> str: ...
        @property
        def field(self) -> _FieldModule.Reader: ...
        @property
        def weatherStation(self) -> _WeatherStationModule.Reader: ...
        @property
        def weatherStationTimeseries(self) -> _TimeSeriesModule.TimeSeriesClient: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def simulationStartDate(self) -> _DateModule.Reader: ...
        @property
        def simulationEndDate(self) -> _DateModule.Reader: ...
        @property
        def irrigationApplied(self) -> bool: ...
        @property
        def fertilizerApplied(self) -> bool: ...
        @property
        def irrigationLevel(self) -> int: ...
        @property
        def fertilizerLevel(self) -> int: ...
        @property
        def plantingDateLevel(self) -> int: ...
        @property
        def environmentalModificationsLevel(self) -> int: ...
        @property
        def initialConditionsLevel(self) -> int: ...
        @property
        def plantingDensityLevel(self) -> int: ...
        @property
        def numberOfBlocksOrReplicates(self) -> int: ...
        @property
        def notes(self) -> str: ...
        @property
        def plots(self) -> Sequence[_PlotModule.Reader]: ...
        @property
        def residue(self) -> _ResidueModule.Reader: ...
        @property
        def initialConditionsLayers(self) -> Sequence[_InitialConditionsLayerModule.Reader]: ...
        @property
        def plantingEvents(self) -> Sequence[_PlantingEventModule.Reader]: ...
        @property
        def harvestEvents(self) -> Sequence[_HarvestEventModule.Reader]: ...
        @property
        def irrigationEvents(self) -> Sequence[_IrrigationEventModule.Reader]: ...
        @property
        def fertilizerEvents(self) -> Sequence[_FertilizerEventModule.Reader]: ...
        @property
        def environmentModifications(self) -> Sequence[_EnvironmentModificationModule.Reader]: ...
        @property
        def experimentId(self) -> str: ...
        @property
        def fieldId(self) -> str: ...
        @property
        def weatherStationId(self) -> str: ...
        @property
        def weatherStationDataset(self) -> str: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _TreatmentModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def id(self) -> str: ...
        @id.setter
        def id(self, value: str) -> None: ...
        @property
        def field(self) -> _FieldModule.Builder: ...
        @field.setter
        def field(self, value: _FieldModule.Builder | _FieldModule.Reader | dict[str, Any]) -> None: ...
        @property
        def weatherStation(self) -> _WeatherStationModule.Builder: ...
        @weatherStation.setter
        def weatherStation(self, value: _WeatherStationModule.Builder | _WeatherStationModule.Reader | dict[str, Any]) -> None: ...
        @property
        def weatherStationTimeseries(self) -> _TimeSeriesModule.TimeSeriesClient: ...
        @weatherStationTimeseries.setter
        def weatherStationTimeseries(self, value: _TimeSeriesModule.TimeSeriesClient | _TimeSeriesModule.Server) -> None: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @name.setter
        def name(self, value: str) -> None: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def simulationStartDate(self) -> _DateModule.Builder: ...
        @simulationStartDate.setter
        def simulationStartDate(self, value: _DateModule.Builder | _DateModule.Reader | dict[str, Any]) -> None: ...
        @property
        def simulationEndDate(self) -> _DateModule.Builder: ...
        @simulationEndDate.setter
        def simulationEndDate(self, value: _DateModule.Builder | _DateModule.Reader | dict[str, Any]) -> None: ...
        @property
        def irrigationApplied(self) -> bool: ...
        @irrigationApplied.setter
        def irrigationApplied(self, value: bool) -> None: ...
        @property
        def fertilizerApplied(self) -> bool: ...
        @fertilizerApplied.setter
        def fertilizerApplied(self, value: bool) -> None: ...
        @property
        def irrigationLevel(self) -> int: ...
        @irrigationLevel.setter
        def irrigationLevel(self, value: int) -> None: ...
        @property
        def fertilizerLevel(self) -> int: ...
        @fertilizerLevel.setter
        def fertilizerLevel(self, value: int) -> None: ...
        @property
        def plantingDateLevel(self) -> int: ...
        @plantingDateLevel.setter
        def plantingDateLevel(self, value: int) -> None: ...
        @property
        def environmentalModificationsLevel(self) -> int: ...
        @environmentalModificationsLevel.setter
        def environmentalModificationsLevel(self, value: int) -> None: ...
        @property
        def initialConditionsLevel(self) -> int: ...
        @initialConditionsLevel.setter
        def initialConditionsLevel(self, value: int) -> None: ...
        @property
        def plantingDensityLevel(self) -> int: ...
        @plantingDensityLevel.setter
        def plantingDensityLevel(self, value: int) -> None: ...
        @property
        def numberOfBlocksOrReplicates(self) -> int: ...
        @numberOfBlocksOrReplicates.setter
        def numberOfBlocksOrReplicates(self, value: int) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @property
        def plots(self) -> MutableSequence[_PlotModule.Builder]: ...
        @plots.setter
        def plots(self, value: Sequence[_PlotModule.Builder | _PlotModule.Reader] | Sequence[dict[str, Any]]) -> None: ...
        @property
        def residue(self) -> _ResidueModule.Builder: ...
        @residue.setter
        def residue(self, value: _ResidueModule.Builder | _ResidueModule.Reader | dict[str, Any]) -> None: ...
        @property
        def initialConditionsLayers(self) -> MutableSequence[_InitialConditionsLayerModule.Builder]: ...
        @initialConditionsLayers.setter
        def initialConditionsLayers(self, value: Sequence[_InitialConditionsLayerModule.Builder | _InitialConditionsLayerModule.Reader] | Sequence[dict[str, Any]]) -> None: ...
        @property
        def plantingEvents(self) -> MutableSequence[_PlantingEventModule.Builder]: ...
        @plantingEvents.setter
        def plantingEvents(self, value: Sequence[_PlantingEventModule.Builder | _PlantingEventModule.Reader] | Sequence[dict[str, Any]]) -> None: ...
        @property
        def harvestEvents(self) -> MutableSequence[_HarvestEventModule.Builder]: ...
        @harvestEvents.setter
        def harvestEvents(self, value: Sequence[_HarvestEventModule.Builder | _HarvestEventModule.Reader] | Sequence[dict[str, Any]]) -> None: ...
        @property
        def irrigationEvents(self) -> MutableSequence[_IrrigationEventModule.Builder]: ...
        @irrigationEvents.setter
        def irrigationEvents(self, value: Sequence[_IrrigationEventModule.Builder | _IrrigationEventModule.Reader] | Sequence[dict[str, Any]]) -> None: ...
        @property
        def fertilizerEvents(self) -> MutableSequence[_FertilizerEventModule.Builder]: ...
        @fertilizerEvents.setter
        def fertilizerEvents(self, value: Sequence[_FertilizerEventModule.Builder | _FertilizerEventModule.Reader] | Sequence[dict[str, Any]]) -> None: ...
        @property
        def environmentModifications(self) -> MutableSequence[_EnvironmentModificationModule.Builder]: ...
        @environmentModifications.setter
        def environmentModifications(self, value: Sequence[_EnvironmentModificationModule.Builder | _EnvironmentModificationModule.Reader] | Sequence[dict[str, Any]]) -> None: ...
        @property
        def experimentId(self) -> str: ...
        @experimentId.setter
        def experimentId(self, value: str) -> None: ...
        @property
        def fieldId(self) -> str: ...
        @fieldId.setter
        def fieldId(self, value: str) -> None: ...
        @property
        def weatherStationId(self) -> str: ...
        @weatherStationId.setter
        def weatherStationId(self, value: str) -> None: ...
        @property
        def weatherStationDataset(self) -> str: ...
        @weatherStationDataset.setter
        def weatherStationDataset(self, value: str) -> None: ...
        @overload
        def init(self, field: Literal["field"], size: int | None = None) -> _FieldModule.Builder: ...
        @overload
        def init(self, field: Literal["weatherStation"], size: int | None = None) -> _WeatherStationModule.Builder: ...
        @overload
        def init(self, field: Literal["simulationStartDate"], size: int | None = None) -> _DateModule.Builder: ...
        @overload
        def init(self, field: Literal["simulationEndDate"], size: int | None = None) -> _DateModule.Builder: ...
        @overload
        def init(self, field: Literal["residue"], size: int | None = None) -> _ResidueModule.Builder: ...
        @overload
        def init(self, field: Literal["plots"], size: int | None = None) -> MutableSequence[_PlotModule.Builder]: ...
        @overload
        def init(self, field: Literal["initialConditionsLayers"], size: int | None = None) -> MutableSequence[_InitialConditionsLayerModule.Builder]: ...
        @overload
        def init(self, field: Literal["plantingEvents"], size: int | None = None) -> MutableSequence[_PlantingEventModule.Builder]: ...
        @overload
        def init(self, field: Literal["harvestEvents"], size: int | None = None) -> MutableSequence[_HarvestEventModule.Builder]: ...
        @overload
        def init(self, field: Literal["irrigationEvents"], size: int | None = None) -> MutableSequence[_IrrigationEventModule.Builder]: ...
        @overload
        def init(self, field: Literal["fertilizerEvents"], size: int | None = None) -> MutableSequence[_FertilizerEventModule.Builder]: ...
        @overload
        def init(self, field: Literal["environmentModifications"], size: int | None = None) -> MutableSequence[_EnvironmentModificationModule.Builder]: ...
        @overload
        def init(self, field: str, size: int | None = None) -> Any: ...
        @override
        def as_reader(self) -> _TreatmentModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        id: str | None = None,
        field: _FieldModule.Builder | dict[str, Any] | None = None,
        weatherStation: _WeatherStationModule.Builder | dict[str, Any] | None = None,
        weatherStationTimeseries: _TimeSeriesModule.TimeSeriesClient | _TimeSeriesModule.Server | None = None,
        name: str | None = None,
        simulationStartDate: _DateModule.Builder | dict[str, Any] | None = None,
        simulationEndDate: _DateModule.Builder | dict[str, Any] | None = None,
        irrigationApplied: bool | None = None,
        fertilizerApplied: bool | None = None,
        irrigationLevel: int | None = None,
        fertilizerLevel: int | None = None,
        plantingDateLevel: int | None = None,
        environmentalModificationsLevel: int | None = None,
        initialConditionsLevel: int | None = None,
        plantingDensityLevel: int | None = None,
        numberOfBlocksOrReplicates: int | None = None,
        notes: str | None = None,
        plots: Sequence[_PlotModule.Builder] | Sequence[dict[str, Any]] | None = None,
        residue: _ResidueModule.Builder | dict[str, Any] | None = None,
        initialConditionsLayers: Sequence[_InitialConditionsLayerModule.Builder] | Sequence[dict[str, Any]] | None = None,
        plantingEvents: Sequence[_PlantingEventModule.Builder] | Sequence[dict[str, Any]] | None = None,
        harvestEvents: Sequence[_HarvestEventModule.Builder] | Sequence[dict[str, Any]] | None = None,
        irrigationEvents: Sequence[_IrrigationEventModule.Builder] | Sequence[dict[str, Any]] | None = None,
        fertilizerEvents: Sequence[_FertilizerEventModule.Builder] | Sequence[dict[str, Any]] | None = None,
        environmentModifications: Sequence[_EnvironmentModificationModule.Builder] | Sequence[dict[str, Any]] | None = None,
        experimentId: str | None = None,
        fieldId: str | None = None,
        weatherStationId: str | None = None,
        weatherStationDataset: str | None = None,
    ) -> _TreatmentModule.Builder: ...

class _ExperimentDescriptionModule(_StructModule):
    TreatmentReader: TypeAlias = _TreatmentModule.Reader
    TreatmentBuilder: TypeAlias = _TreatmentModule.Builder
    Treatment: _TreatmentModule
    class Reader(_DynamicStructReader):
        @property
        def id(self) -> str: ...
        @property
        def suiteId(self) -> str: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def researchInfrastructureName(self) -> str: ...
        @property
        def instituteName(self) -> str: ...
        @property
        def researchUnitName(self) -> str: ...
        @property
        def experimentalFacilityName(self) -> str: ...
        @property
        def siteName(self) -> str: ...
        @property
        def siteType(self) -> str: ...
        @property
        def mainExperimentFactor(self) -> str: ...
        @property
        def experimentalFactorCombinations(self) -> str: ...
        @property
        def experimentType(self) -> str: ...
        @property
        def managementType(self) -> str: ...
        @property
        def croppingSystem(self) -> str: ...
        @property
        def plantingYear(self) -> int: ...
        @property
        def harvestOperationYear(self) -> int: ...
        @property
        def notes(self) -> str: ...
        @property
        def treatments(self) -> Sequence[_TreatmentModule.Reader]: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _ExperimentDescriptionModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def id(self) -> str: ...
        @id.setter
        def id(self, value: str) -> None: ...
        @property
        def suiteId(self) -> str: ...
        @suiteId.setter
        def suiteId(self, value: str) -> None: ...
        @property
        def name(self) -> str: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @name.setter
        def name(self, value: str) -> None: ...  # pyright: ignore[reportIncompatibleVariableOverride,reportIncompatibleMethodOverride]
        @property
        def researchInfrastructureName(self) -> str: ...
        @researchInfrastructureName.setter
        def researchInfrastructureName(self, value: str) -> None: ...
        @property
        def instituteName(self) -> str: ...
        @instituteName.setter
        def instituteName(self, value: str) -> None: ...
        @property
        def researchUnitName(self) -> str: ...
        @researchUnitName.setter
        def researchUnitName(self, value: str) -> None: ...
        @property
        def experimentalFacilityName(self) -> str: ...
        @experimentalFacilityName.setter
        def experimentalFacilityName(self, value: str) -> None: ...
        @property
        def siteName(self) -> str: ...
        @siteName.setter
        def siteName(self, value: str) -> None: ...
        @property
        def siteType(self) -> str: ...
        @siteType.setter
        def siteType(self, value: str) -> None: ...
        @property
        def mainExperimentFactor(self) -> str: ...
        @mainExperimentFactor.setter
        def mainExperimentFactor(self, value: str) -> None: ...
        @property
        def experimentalFactorCombinations(self) -> str: ...
        @experimentalFactorCombinations.setter
        def experimentalFactorCombinations(self, value: str) -> None: ...
        @property
        def experimentType(self) -> str: ...
        @experimentType.setter
        def experimentType(self, value: str) -> None: ...
        @property
        def managementType(self) -> str: ...
        @managementType.setter
        def managementType(self, value: str) -> None: ...
        @property
        def croppingSystem(self) -> str: ...
        @croppingSystem.setter
        def croppingSystem(self, value: str) -> None: ...
        @property
        def plantingYear(self) -> int: ...
        @plantingYear.setter
        def plantingYear(self, value: int) -> None: ...
        @property
        def harvestOperationYear(self) -> int: ...
        @harvestOperationYear.setter
        def harvestOperationYear(self, value: int) -> None: ...
        @property
        def notes(self) -> str: ...
        @notes.setter
        def notes(self, value: str) -> None: ...
        @property
        def treatments(self) -> MutableSequence[_TreatmentModule.Builder]: ...
        @treatments.setter
        def treatments(self, value: Sequence[_TreatmentModule.Builder | _TreatmentModule.Reader] | Sequence[dict[str, Any]]) -> None: ...
        def init(self, field: Literal["treatments"], size: int | None = None) -> MutableSequence[_TreatmentModule.Builder]: ...
        @override
        def as_reader(self) -> _ExperimentDescriptionModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        id: str | None = None,
        suiteId: str | None = None,
        name: str | None = None,
        researchInfrastructureName: str | None = None,
        instituteName: str | None = None,
        researchUnitName: str | None = None,
        experimentalFacilityName: str | None = None,
        siteName: str | None = None,
        siteType: str | None = None,
        mainExperimentFactor: str | None = None,
        experimentalFactorCombinations: str | None = None,
        experimentType: str | None = None,
        managementType: str | None = None,
        croppingSystem: str | None = None,
        plantingYear: int | None = None,
        harvestOperationYear: int | None = None,
        notes: str | None = None,
        treatments: Sequence[_TreatmentModule.Builder] | Sequence[dict[str, Any]] | None = None,
    ) -> _ExperimentDescriptionModule.Builder: ...

ExperimentDescriptionReader: TypeAlias = _ExperimentDescriptionModule.Reader
ExperimentDescriptionBuilder: TypeAlias = _ExperimentDescriptionModule.Builder
ExperimentDescription: _ExperimentDescriptionModule
