"""This is an automatically generated stub for `geo.capnp`."""

from __future__ import annotations

from enum import Enum
from typing import Any, Generic, Literal, TypeAlias, TypeVar, overload, override

from capnp.lib.capnp import (
    _DynamicCapabilityClient,
    _DynamicCapabilityServer,
    _DynamicStructBuilder,
    _DynamicStructReader,
    _InterfaceModule,
    _Request,
    _StructModule,
)

_CoordinateType = TypeVar("_CoordinateType")

class _CoordTypeModule(Enum):
    gk = 0
    utm = 1
    latlon = 2

CoordType: TypeAlias = _CoordTypeModule

class _EPSGModule(_StructModule):
    wgs84: int
    utm21S: int
    utm32N: int
    gk5: int
    gk4: int
    gk3: int
    class Reader(_DynamicStructReader):
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _EPSGModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @override
        def as_reader(self) -> _EPSGModule.Reader: ...

    @override
    def new_message(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _EPSGModule.Builder: ...

EPSGReader: TypeAlias = _EPSGModule.Reader
EPSGBuilder: TypeAlias = _EPSGModule.Builder
EPSG: _EPSGModule

class _UTMCoordModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def zone(self) -> int: ...
        @property
        def latitudeBand(self) -> str: ...
        @property
        def r(self) -> float: ...
        @property
        def h(self) -> float: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _UTMCoordModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def zone(self) -> int: ...
        @zone.setter
        def zone(self, value: int) -> None: ...
        @property
        def latitudeBand(self) -> str: ...
        @latitudeBand.setter
        def latitudeBand(self, value: str) -> None: ...
        @property
        def r(self) -> float: ...
        @r.setter
        def r(self, value: float) -> None: ...
        @property
        def h(self) -> float: ...
        @h.setter
        def h(self, value: float) -> None: ...
        @override
        def as_reader(self) -> _UTMCoordModule.Reader: ...

    @override
    def new_message(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None, zone: int | None = None, latitudeBand: str | None = None, r: float | None = None, h: float | None = None) -> _UTMCoordModule.Builder: ...

UTMCoordReader: TypeAlias = _UTMCoordModule.Reader
UTMCoordBuilder: TypeAlias = _UTMCoordModule.Builder
UTMCoord: _UTMCoordModule

class _LatLonCoordModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def lat(self) -> float: ...
        @property
        def lon(self) -> float: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _LatLonCoordModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def lat(self) -> float: ...
        @lat.setter
        def lat(self, value: float) -> None: ...
        @property
        def lon(self) -> float: ...
        @lon.setter
        def lon(self, value: float) -> None: ...
        @override
        def as_reader(self) -> _LatLonCoordModule.Reader: ...

    @override
    def new_message(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None, lat: float | None = None, lon: float | None = None) -> _LatLonCoordModule.Builder: ...

LatLonCoordReader: TypeAlias = _LatLonCoordModule.Reader
LatLonCoordBuilder: TypeAlias = _LatLonCoordModule.Builder
LatLonCoord: _LatLonCoordModule

class _GKCoordModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def meridianNo(self) -> int: ...
        @property
        def r(self) -> float: ...
        @property
        def h(self) -> float: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _GKCoordModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def meridianNo(self) -> int: ...
        @meridianNo.setter
        def meridianNo(self, value: int) -> None: ...
        @property
        def r(self) -> float: ...
        @r.setter
        def r(self, value: float) -> None: ...
        @property
        def h(self) -> float: ...
        @h.setter
        def h(self, value: float) -> None: ...
        @override
        def as_reader(self) -> _GKCoordModule.Reader: ...

    @override
    def new_message(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None, meridianNo: int | None = None, r: float | None = None, h: float | None = None) -> _GKCoordModule.Builder: ...

GKCoordReader: TypeAlias = _GKCoordModule.Reader
GKCoordBuilder: TypeAlias = _GKCoordModule.Builder
GKCoord: _GKCoordModule

class _Point2DModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def x(self) -> float: ...
        @property
        def y(self) -> float: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _Point2DModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def x(self) -> float: ...
        @x.setter
        def x(self, value: float) -> None: ...
        @property
        def y(self) -> float: ...
        @y.setter
        def y(self, value: float) -> None: ...
        @override
        def as_reader(self) -> _Point2DModule.Reader: ...

    @override
    def new_message(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None, x: float | None = None, y: float | None = None) -> _Point2DModule.Builder: ...

Point2DReader: TypeAlias = _Point2DModule.Reader
Point2DBuilder: TypeAlias = _Point2DModule.Builder
Point2D: _Point2DModule

class _RowColModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def row(self) -> int: ...
        @property
        def col(self) -> int: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _RowColModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def row(self) -> int: ...
        @row.setter
        def row(self, value: int) -> None: ...
        @property
        def col(self) -> int: ...
        @col.setter
        def col(self, value: int) -> None: ...
        @override
        def as_reader(self) -> _RowColModule.Reader: ...

    @override
    def new_message(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None, row: int | None = None, col: int | None = None) -> _RowColModule.Builder: ...

RowColReader: TypeAlias = _RowColModule.Reader
RowColBuilder: TypeAlias = _RowColModule.Builder
RowCol: _RowColModule

class _CoordModule(_StructModule):
    class Reader(_DynamicStructReader):
        @property
        def gk(self) -> _GKCoordModule.Reader: ...
        @property
        def latlon(self) -> _LatLonCoordModule.Reader: ...
        @property
        def utm(self) -> _UTMCoordModule.Reader: ...
        @property
        def p2D(self) -> _Point2DModule.Reader: ...
        @property
        def rowcol(self) -> _RowColModule.Reader: ...
        @override
        def which(self) -> Literal["gk", "latlon", "utm", "p2D", "rowcol"]: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _CoordModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def gk(self) -> _GKCoordModule.Builder: ...
        @gk.setter
        def gk(self, value: _GKCoordModule.Builder | _GKCoordModule.Reader | dict[str, Any]) -> None: ...
        @property
        def latlon(self) -> _LatLonCoordModule.Builder: ...
        @latlon.setter
        def latlon(self, value: _LatLonCoordModule.Builder | _LatLonCoordModule.Reader | dict[str, Any]) -> None: ...
        @property
        def utm(self) -> _UTMCoordModule.Builder: ...
        @utm.setter
        def utm(self, value: _UTMCoordModule.Builder | _UTMCoordModule.Reader | dict[str, Any]) -> None: ...
        @property
        def p2D(self) -> _Point2DModule.Builder: ...
        @p2D.setter
        def p2D(self, value: _Point2DModule.Builder | _Point2DModule.Reader | dict[str, Any]) -> None: ...
        @property
        def rowcol(self) -> _RowColModule.Builder: ...
        @rowcol.setter
        def rowcol(self, value: _RowColModule.Builder | _RowColModule.Reader | dict[str, Any]) -> None: ...
        @override
        def which(self) -> Literal["gk", "latlon", "utm", "p2D", "rowcol"]: ...
        @overload
        def init(self, field: Literal["gk"], size: int | None = None) -> _GKCoordModule.Builder: ...
        @overload
        def init(self, field: Literal["latlon"], size: int | None = None) -> _LatLonCoordModule.Builder: ...
        @overload
        def init(self, field: Literal["utm"], size: int | None = None) -> _UTMCoordModule.Builder: ...
        @overload
        def init(self, field: Literal["p2D"], size: int | None = None) -> _Point2DModule.Builder: ...
        @overload
        def init(self, field: Literal["rowcol"], size: int | None = None) -> _RowColModule.Builder: ...
        @overload
        def init(self, field: str, size: int | None = None) -> Any: ...
        @override
        def as_reader(self) -> _CoordModule.Reader: ...

    @override
    def new_message(
        self,
        num_first_segment_words: int | None = None,
        allocate_seg_callable: Any = None,
        gk: _GKCoordModule.Builder | dict[str, Any] | None = None,
        latlon: _LatLonCoordModule.Builder | dict[str, Any] | None = None,
        utm: _UTMCoordModule.Builder | dict[str, Any] | None = None,
        p2D: _Point2DModule.Builder | dict[str, Any] | None = None,
        rowcol: _RowColModule.Builder | dict[str, Any] | None = None,
    ) -> _CoordModule.Builder: ...

CoordReader: TypeAlias = _CoordModule.Reader
CoordBuilder: TypeAlias = _CoordModule.Builder
Coord: _CoordModule

class _RectBoundsModule(Generic[_CoordinateType], _StructModule):
    class Reader(_DynamicStructReader):
        @property
        def tl(self) -> _CoordinateType: ...
        @property
        def br(self) -> _CoordinateType: ...
        @override
        def as_builder(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None) -> _RectBoundsModule.Builder: ...

    class Builder(_DynamicStructBuilder):
        @property
        def tl(self) -> _CoordinateType: ...
        @tl.setter
        def tl(self, value: _CoordinateType) -> None: ...
        @property
        def br(self) -> _CoordinateType: ...
        @br.setter
        def br(self, value: _CoordinateType) -> None: ...
        @override
        def as_reader(self) -> _RectBoundsModule.Reader: ...

    @override
    def new_message(self, num_first_segment_words: int | None = None, allocate_seg_callable: Any = None, tl: _CoordinateType | None = None, br: _CoordinateType | None = None) -> _RectBoundsModule.Builder: ...

RectBoundsReader: TypeAlias = _RectBoundsModule.Reader
RectBoundsBuilder: TypeAlias = _RectBoundsModule.Builder
RectBounds: _RectBoundsModule
